openkfw/TruBudget

provisioning/src/data/prod/ecole.json, provisioning/src/data/prod/gavi.json, provisioning/src/data/prod/school.json
=> provisioning: Fix test data for prod

e2e-test/cypress/integration/overview_spec.js
=> e2e-test: Fix value for overview spec

api/src/user_authenticate.ts
=> api: Increase lifespan of JWT to 8h

frontend/src/pages/Documents/DocumentUpload.js
=> Fix upload button issue for Firefox

api/src/notification_list.ts, frontend/src/pages/Notifications/LiveNotificationContainer.js, frontend/src/pages/Notifications/NotificationPageContainer.js, frontend/src/pages/Notifications/actions.js, frontend/src/pages/Notifications/reducer.js
1. The **schema** of the notification.list endpoint has to be updated so the response contains all fields again.
2. Live notifications on the notification page fetch wrong count of new notifications. The notification list is not instantly updated when fetching live updates so the **live update can be disabled** on the notification page
=> Fix-notifications-endpoint

provisioning/src/lib.js
=> provisioning: add status code 400 to the retry list

api/src/service/domain/workflow/workflowitem_update.spec.ts, api/src/service/domain/workflow/workflowitem_updated.ts
Currently a workflowitem-update that refers to an existing document is accepted, even if the provided document hash differs from what is stored on the chain. The document could never be overwritten, but this PR means to reject such an update altogether.
=> API: Reject workflowitem update when document would be overwritten

README.md
=> doc: Add link to gitter in README

api/src/service/domain/workflow/workflowitem.ts, api/src/service/domain/workflow/workflowitem_updated.ts, api/src/workflowitem_update.ts
Set billingData, amount, currency and exchange rate as forbidden when
the amountType of an update is 'N/A'. This fixes the error during
provisioning.
=> api: Fix schema for workflowitem_update

.gitignore, .travis.yml, dangerfile.js, package-lock.json, package.json
This MR adds the [danger](https://danger.systems/js) module to the project with following check:
- enforce changelog.md
Also added the possibility to skip the build (build and push docker images) and notification (trigger external webhook) stage via `skip-build` via commit message
closes #249
=> Add danger js for enforcing changelog

frontend/src/pages/Common/Budget.js, frontend/src/pages/Common/CreationDialog.js, frontend/src/pages/SubProjects/ProjectDetails.js, frontend/src/pages/SubProjects/SubProjectTable.js, frontend/src/pages/Workflows/SubProjectDetails.js
Previous merges cause issues on creation dialogs.
This PR fixes:
- responsive design workflowitem creation dialog is too small
- budget input field of dialogs is misaligned
=> UI: bug fixes creation dialog

CHANGELOG.md, blockchain/Dockerfile, doc/tutorials/installation/bare-metal-installation.md
This PR updates the Multichain Version used by TruBudget to the current version (2.0.1)
=> bc: updated mc version to 2.0.1

frontend/src/languages/french.js, frontend/src/pages/Common/Budget.js
=> Update french translations

CHANGELOG.md, frontend/src/pages/Documents/DocumentOverviewContainer.js, frontend/src/pages/Workflows/WorkflowDialogContainer.js, frontend/src/pages/Workflows/reducer.js
=> Existing documents disappear when adding new ones

frontend/src/pages/Common/History/ScrollingHistory.js
Issue:
1. User opens the history drawer of a project A
2. User opens the history drawer of project B
3. History items of project A are shown
Also implement a centered loading indicator when fetching history items
=> UI: Fetch history items after history drawer did mount

frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Analytics/ProjectAnalytics.js, frontend/src/pages/Analytics/SubProjectAnalytics.js, frontend/src/pages/Common/Budget.js, frontend/src/pages/Nodes/NodesTable.js, frontend/src/pages/SubProjects/ProjectDetails.js, frontend/src/pages/Users/UserDialogContent.js, frontend/src/pages/Users/UsersTable.js, frontend/src/pages/Workflows/SubProjectDetails.js
Move the 'organization' string from 'strings.users.organization' to
'strings.common.organization'.
Closes #286
=> ui: Move organization string to 'common'

.travis.yml, dangerfile.js
- If there are additional console logs in the API
- If there are new TODOs in any of the files
- Created async block to execute async calls like
'structuredDiffForFile'
- Use Node 11 for Danger in order to use 'Array.prototype.flat()'
- Created functions to extract additions, deletions and normal code from
file changes
Closes #255
=> danger: Add check for new TODOs and console logs in API

CHANGELOG.md, e2e-test/cypress/integration/notification_spec.js, e2e-test/cypress/integration/workflowitem_history_spec.js, frontend/src/helper.js, frontend/src/index.js, frontend/src/pages/Common/HistoryList.js, frontend/src/pages/Documents/DocumentOverview.js, frontend/src/pages/Notifications/FlyInNotifications.js, frontend/src/pages/Notifications/NotificationList.js, frontend/src/pages/Notifications/NotificationListItems.js, frontend/src/pages/Notifications/NotificationPage.js, frontend/src/pages/Notifications/NotificationPageContainer.js, frontend/src/pages/Notifications/actions.js, frontend/src/pages/Notifications/helper.js, frontend/src/pages/Notifications/reducer.js, frontend/src/pages/Workflows/WorkflowAssigneeContainer.js, frontend/src/sagas.js
The implementation for fetching notifications is changed. Instead of
keeping offset and limit in the state, the page is fetched by page
number instead (similar to the history).
The issue of overfetching on the last page was solved by calculating the
number of remaining items to be fetched for the last page.
Closes #288
When the name of the assignee is too long it gets shortened by ellipses
in the workflow item table.
Closes #299
The displaynames of the project and subproject are now displayed on the
notification page for each entry. If the user does not have permissions
to see the project/subproject it gets replaced by the word "Redacted".
Closes #298
If the user does not have the permission to see a
project/subproject/workflowitem, the displayname is not displayed in the
notification and …
=> Fix notification issues

api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json
Due to security concerns the axios version was updated to 0.19.0. For
further information see https://nvd.nist.gov/vuln/detail/CVE-2019-10742
=> Update axios version

CHANGELOG.md, api/src/user_list.ts, doc/wiki/User-Guide/Users-Groups/User.md, e2e-test/cypress/integration/change_user_password_spec.js, e2e-test/cypress/integration/groups_spec.js, e2e-test/cypress/integration/users_spec.js, e2e-test/cypress/support/commands.js, frontend/src/api.js, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Common/Password.js, frontend/src/pages/Login/LoginPage.js, frontend/src/pages/Login/LoginPageContainer.js, frontend/src/pages/Login/actions.js, frontend/src/pages/Users/Dialog.js, frontend/src/pages/Users/DialogContainer.js, frontend/src/pages/Users/UserDialogContent.js, frontend/src/pages/Users/UserManagementContainer.js, frontend/src/pages/Users/UserPasswordChangeDialogContent.js, frontend/src/pages/Users/Users.js, frontend/src/pages/Users/UsersTable.js, frontend/src/pages/Users/actions.js, frontend/src/pages/Users/reducer.js, frontend/src/pages/Workflows/WorkflowDetails.js, frontend/src/sagas.js
A user can now change the password for each user, where he/she has the permission to do so (including his/her own password). The password can be changed on the user overview page. 
The user has to enter his/her own password first as security measure. 
Closes #325 
There are new E2E tests which specifically test this feature. Otherwise, the password can be changed manually by clicking on the edit symbol next to the permissions symbol, entering the current password and then entering the new one.
=> ui: Change Password Feature

CHANGELOG.md, api/src/subproject_view_details.ts, e2e-test/cypress/integration/subproject_permissions_spec.js, e2e-test/cypress/support/commands.js, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Navbar/MainNavbarNavigation.js, frontend/src/pages/Workflows/SubProjectDetails.js
When a user has the permission to see subproject details, but not the permissions for the parent project, he/she can still view the subproject details page as expected. 
Create a project with no permissions for e.g. "UserA", then create a subproject and grant permissions to see the subproject details to "UserA". Log in as "UserA" and open the subproject details page via the URL and the page should display the subproject details as expected.
=> View subproject details correctly

CHANGELOG.md, api/postman/README.md, api/postman/TruBudget.postman_collection.json, api/postman/TruBudget.postman_environment.json
More details in #199
Close #199
=> update postman collection and environment

api/package-lock.json, e2e-test/cypress/integration/currencies_spec.js, e2e-test/cypress/integration/navigation_spec.js, e2e-test/cypress/integration/overview_spec.js, e2e-test/cypress/integration/project_tags.js, frontend/package-lock.json, frontend/package.json, frontend/src/pages/Overview/OverviewTable.js, frontend/src/pages/Overview/ProjectCard.js
* Create new component for project card
* Set fixed height of project cards
* Make project cards slightly wider
* Make content of project cards scrollable
* Refactor styles
Closes #354 
Closes #352 
Closes #357
=> Refactor and change project cards

CHANGELOG.md, api/src/service/domain/workflow/workflowitem_create.spec.ts, api/src/service/domain/workflow/workflowitem_create.ts, e2e-test/cypress/integration/subproject_budget_spec.js, e2e-test/cypress/integration/workflowitem_create_spec.js, frontend/src/pages/Workflows/Workflow.js, frontend/src/pages/Workflows/WorkflowContainer.js
* ui: disable create workflow item button for root
* api: return precondition error if root tries to add a workflow item
* add tests
Tests workflowitem_create.spec.ts and workflowitem_edit_spec.js are added
Closes #380
=> Prohibit root from adding workflowitems

CHANGELOG.md, e2e-test/cypress/fixtures/testdata.json, e2e-test/cypress/integration/global_permissions_spec.js, e2e-test/cypress/integration/subproject_permissions_spec.js, e2e-test/cypress/integration/workflowitem_permissions_spec.js, frontend/src/pages/Common/Permissions/PermissionDialog.js, frontend/src/pages/Common/Permissions/PermissionSelection.js, frontend/src/pages/Common/Permissions/PermissionsTable.js, frontend/src/pages/Overview/ProjectPermissionsContainer.js, frontend/src/pages/Overview/actions.js, frontend/src/pages/Overview/reducer.js, frontend/src/pages/SubProjects/SubprojectPermissionsContainer.js, frontend/src/pages/SubProjects/actions.js, frontend/src/pages/SubProjects/reducer.js, frontend/src/pages/Users/Dialog.js, frontend/src/pages/Users/DialogContainer.js, frontend/src/pages/Users/GlobalPermissions.js, frontend/src/pages/Users/actions.js, frontend/src/pages/Users/reducer.js, frontend/src/pages/Workflows/WorkflowEditDrawer.js, frontend/src/pages/Workflows/WorkflowItem.js, frontend/src/pages/Workflows/WorkflowItemPermissionsContainer.js, frontend/src/pages/Workflows/actions.js, frontend/src/pages/Workflows/reducer.js
The user now has to submit the changes that were made to the permissions of a project, subproject or workflow item. 
Closes #245 
Change the permissions for e.g. a project, click submit and the permission should have changed. Try the same and hit cancel instead and the permissions should be the same as before opening the dialog.
=> Rework editing of permissions

CHANGELOG.md, api/src/organization/organization.ts, api/src/service/domain/organization/user_create.spec.ts, api/src/service/domain/organization/user_create.ts, api/src/service/user_create.ts, e2e-test/cypress/integration/login_spec.js
If a user shall be created via api with an organization that doesn't exist the api response is an error but also creates the user.
Closes #358
=> api: add check if organization does exist

frontend/package-lock.json
https://travis-ci.com/github/openkfw/TruBudget/jobs/296908790
=> update npm package versions in lockfile

api/package-lock.json, blockchain/package-lock.json, e2e-test/package-lock.json, package-lock.json
Merge dependabot branches into new branch to fix e2e-tests and run npm audit fix
=> Security update

.travis.yml, scripts/pipeline/audit.sh
=> refactor npm audit job

frontend/package-lock.json
=> ui: Audit fix for http-proxy

e2e-test/cypress/integration/email_service_spec.js, frontend/package.json, frontend/src/pages/Login/LoginPageContainer.js, frontend/src/pages/Navbar/NavbarContainer.js
=> Fix email readiness error

CHANGELOG.md, e2e-test/cypress/integration/project_search_spec.js, frontend/src/pages/Navbar/ProjectSearch.js, frontend/src/pages/Navbar/RightNavbarNavigation.js
=> Hide project search button

CHANGELOG.md, frontend/src/pages/Workflows/WorkflowItem.js
=> Hide badge when sorting wItems

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package.json
=> Release 1.11.0

CHANGELOG.md, api/src/project_create.ts, api/src/subproject_create.ts, api/src/workflowitem_create.ts
=> Prevent creating closed project/subproject/witem

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json, provisioning/package-lock.json, provisioning/package.json
=> Bump to v1.12.0

frontend/public/app.css, frontend/src/pages/Main/Main.js, frontend/src/pages/Navbar/MainNavbarNavigation.js, frontend/src/pages/Navbar/RightNavbarNavigation.js, frontend/src/pages/SubProjects/SubProjectTable.js, frontend/src/pages/SubProjects/SubProjects.js, frontend/src/pages/Users/Users.js, frontend/src/pages/Users/UsersTable.js
=> ui: fix style bugs in navbar, background and tables (subproject and user tables) for smaller screens (tablet)

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json
=> Bump to v1.13.0

CHANGELOG.md, frontend/package-lock.json, frontend/src/localStorage.js, frontend/src/sagas.js
=> UI: Fix email-service bug

CHANGELOG.md, frontend/src/api.js
- the validateUrl function filters parameters that are empty or undefined
Closes #549
=> ui: Add url validation to filter empty parameters

e2e-test/cypress/integration/currencies_spec.js, e2e-test/cypress/integration/project_budget_spec.js, e2e-test/cypress/integration/subproject_budget_spec.js, frontend/src/helper.js, frontend/src/languages/german.js, frontend/src/pages/Common/Budget.js, frontend/src/pages/Overview/ProjectDialog.js, frontend/src/pages/Overview/ProjectDialogContainer.js, frontend/src/pages/Overview/ProjectDialogContent.js, frontend/src/pages/Overview/actions.js, frontend/src/pages/Overview/reducer.js, frontend/src/pages/SubProjects/ProjectDetails.js, frontend/src/pages/SubProjects/SubprojectDialog.js, frontend/src/pages/SubProjects/SubprojectDialogContainer.js, frontend/src/pages/SubProjects/SubprojectDialogContent.js, frontend/src/pages/SubProjects/actions.js, frontend/src/pages/SubProjects/reducer.js, frontend/src/pages/Workflows/SubProjectDetails.js, frontend/src/sagas.js
Instead of managing the state locally in the budget.js file, redux should be used.
Closes #208 
Closes #533 
Closes #534
=> Refactor budget.js with Redux

CHANGELOG.md, api/src/group_list.ts, api/src/group_permissions_list.ts, api/src/index.ts, api/src/service/group_permissions_list.ts, e2e-test/cypress/integration/groups_spec.js, frontend/src/pages/Users/GroupTable.js
=> Group permission bug fix

CHANGELOG.md, e2e-test/cypress/integration/excel_export_spec.js, e2e-test/cypress/plugins/index.js, e2e-test/package-lock.json, e2e-test/package.json, excel-export/package-lock.json, excel-export/package.json, excel-export/src/excel.ts, excel-export/src/index.ts, excel-export/src/languages/english.ts, excel-export/src/languages/french.ts, excel-export/src/languages/georgian.ts, excel-export/src/languages/german.ts, excel-export/src/languages/portuguese.ts, excel-export/src/localizeStrings.ts, frontend/src/api.js
Frontend: 
- the language the user is logged in with is sent from the frontend to the excel-export server as a query parameter in the get request
Excel Export: 
- implemented the 'localized-strings' module and created translation files for all languages used in TruBudget
- when the export request arrives, the endpoint is checked and if it contains a language, then the language is set (index.ts)
- the column and sheet names of the table are set using the correct language (excel.ts)
e2e-test: 
- The excel file is downloaded in the cypress fixtures folder, is checked for the appropriate language using cy.tasks and then deleted
Closes #567
=> Excel language feature

doc/tutorials/contribute/Contributor-Guide.md
updated contributor-guide.md for windows user.
content updated in api & provisioning section.
=> doc: Update Contributor-Guide.md for windows user

api/Dockerfile, api/package-lock.json, api/package.json
Updated the package.json in api folder.
updated "sodium-native": "^3.2.0".
=> api: updated the package.json

CHANGELOG.md, frontend/src/pages/Common/TextInputWithIcon.js, frontend/src/pages/Common/UserSelection.js
This PR fixes some css bugs in the labels in some translations
Closes #625
=> ui: Fix css for labels

e2e-test/cypress/integration/groups_spec.js, frontend/src/pages/Users/GroupTable.js
Randomized group id in group_spec.js so tests can run multiple times.
Closes #621
=> e2e: randomizing group name

CHANGELOG.md, e2e-test/cypress/integration/language_spec.js, excel-export/package-lock.json, excel-export/package.json, excel-export/src/api.ts, excel-export/src/excel.ts, excel-export/src/helper.ts, excel-export/src/languages/english.ts, excel-export/src/languages/french.ts, excel-export/src/languages/georgian.ts, excel-export/src/languages/german.ts, excel-export/src/languages/portuguese.ts, frontend/src/languages/french.js
This PR:
- fixes some ui and excel export translations
- maps results from the api in the export service to the correct translations for the excel export
- adds a dev script to package.json
Closes #655
=> excel-export/ui: Fix translations

CHANGELOG.md, e2e-test/cypress/integration/scroll_back_to_top_spec.js, frontend/src/pages/Common/ScrollTop.js, frontend/src/pages/Main/Main.js, frontend/src/pages/Navbar/Navbar.js
Add Fab button at the bottom and scroll back to the top.
New file added ScrollTop.js
Closes #579
=> UI: scroll back to top button added

api/src/service/domain/workflow/project_history_get.spec.ts, api/src/service/domain/workflow/project_history_get.ts, api/src/service/domain/workflow/subproject_history_get.spec.ts, api/src/service/domain/workflow/subproject_history_get.ts, api/src/service/domain/workflow/workflowitem_history_get.spec.ts, api/src/service/domain/workflow/workflowitem_history_get.ts
=> api:Remove unnecessary intents from history api

frontend/package-lock.json, frontend/package.json, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Confirmation/ConfirmationContainer.js, frontend/src/pages/Confirmation/actions.js, frontend/src/pages/Confirmation/reducer.js, frontend/src/pages/Confirmation/validation.js, frontend/src/sagas.js
Implementation of JOI validations in frontend
The current PR is raised only for createProject.
Section based errors are displayed
=> UI - implementaion of joi validation in project

.vscode/launch.json, api/package.json, doc/installation/Developer-Setup.md, doc/installation/README.md, docker-compose/development/docker-compose.yml, frontend/Dockerfile.dev, scripts/development/start-dev.sh
* Brings another option to run application in dev mode with single command
* Frontend and API are supporting live reloading
* Prepare setup for debug in VS Code
* See Contributor guide for more explanation
* Note: Besides debugging the api containerized, container debugging will be resolved in [issue 667](https://github.com/openkfw/TruBudget/issues/667)
Closes #641
=> Docker Compose in development mode

api/package-lock.json, api/package.json, api/src/scripts/joiGenerator.ts
PR adds generator of Joi definitions from Swagger.
in /api you can use npm run generate-joi {name_of_the_file_from_root} e.g. npm run generate-joi project_update.ts
This will display the diff between existing definition and generated definition. If you want to rewrite the definition in file just add "r" to the command e.g. npm run generate-joi project_update.ts r.
Sometimes there is a need to update Swagger. E.g. if you want to have .allow('') in Joi, based on swagger documentation you have to specify minLength: 0 in Swgger.
Sometimes you might want custom Joi definition. In that case just add property to swagger e.g. "x-joi-replace": "MyCustomDefinition". Also you can use x-joi-add to just add custom definition to the end of generated Joi definition.
Closes #665
=> api:generator of joi definitions

api/.eslintrc.yaml
This PR extends comments in eslint configuration file for API module.
=> api: Extend comments in api eslintrc

frontend/src/pages/Main/Main.js
This PR fixes a bug in the background color
=> ui: Fix background color

preCommit.sh, provisioning/.eslintrc.yaml, provisioning/package-lock.json, provisioning/package.json, provisioning/src/api.js, provisioning/src/index.js, provisioning/src/lib.js
Added eslint config in provisioning. Added `npm run lint` and `npm run lint:fix` commands.
Fixed several issues in provisioning.
Closes #674
=> provisioning:eslint congifuration + fixes

frontend/src/pages/Confirmation/DialogButtons.js, frontend/src/pages/Workflows/SubProjectDetails.js
=> Default assignee label fix

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json
=> Bump to version 1.17.0

frontend/src/languages/english.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js
workflow_budget: "Budget amount"
translation updated in English, German, Georgian and Portuguese files.
=> ui: update workflow budget amount label

.github/ISSUE_TEMPLATE/1.technical.md
This PR adds an issue template for technical work.
=> github: Add template for technical issues

e2e-test/cypress/integration/workflowitem_edit_spec.js
The iso date format was incorrect. The changes resolves the issue
=> hotfix e2e-test: fix iso date format

.vscode/settings.json, blockchain/.eslintrc.yaml, blockchain/.vscode/settings.json, blockchain/package-lock.json, blockchain/package.json, blockchain/src/connectToChain.js, blockchain/src/createChain.js, blockchain/src/index.js, blockchain/src/kubernetesClient.js, blockchain/src/kubernetesClient.spec.js, blockchain/src/md5.js, blockchain/src/multichain-feed/email-notifications/createAuthToken.js, blockchain/src/multichain-feed/email-notifications/logger.js, blockchain/src/multichain-feed/email-notifications/sendNotifications.js, blockchain/src/shell.js
This PR adds ESLint settings for blockchain module with similar rules and temporary overrides like in other modules.
PR adds required libraries to blockchain, `npm i` required.
PR contains a few fixes for some eslint errors. For example `arguments` in `blockchain/src/multichain-feed/email-notifications/sendNotifications.js` renamed to `args`, because `arguments`, as it turns out,  is a reserved keyword in JS.
Closes #675
=> blockchain: Setup eslint and fix some errs

api/package-lock.json, api/src/system/createBackup.ts, api/src/system/restoreBackup.ts, blockchain/package-lock.json, blockchain/package.json, blockchain/src/index.js, blockchain/src/sha256.js, blockchain/src/shell.js, docker-compose/development/docker-compose-slim.yml, scripts/development/start-dev-slim.sh
SHA256 hashing for new created backups.
Compatibility with old MD5 hashing on backups restore.
New slim docker-compose to quick start only essential services.
Closes #693
Closes #513
=> bc,api:SHA256 hashing for backups

CHANGELOG.md, e2e-test/cypress/integration/workflowitem_edit_spec.js, frontend/src/pages/Common/DatePicker.js
=> ui: update workflow edit invalid date

CHANGELOG.md, frontend/src/pages/Workflows/WorkflowItem.js
=> 707 chkboxes workflowitems

api/src/service/domain/workflow/project_history_get.spec.ts, api/src/service/domain/workflow/project_history_get.ts, api/src/service/domain/workflow/subproject_history_get.spec.ts, api/src/service/domain/workflow/subproject_history_get.ts, api/src/service/domain/workflow/workflowitem_history_get.spec.ts, api/src/service/domain/workflow/workflowitem_history_get.ts
This PR reverts a commit that is a cause of the issue.
https://github.com/openkfw/TruBudget/pull/605/files
Closes #706
=> api: Revert commit that caused the issue

CHANGELOG.md, e2e-test/cypress/integration/groups_spec.js, frontend/src/pages/Common/UserSelection.js, frontend/src/pages/Users/GroupDialogContent.js
This PR 
- Adds multiple selection with checkboxes to the user selection for groups
- Also converts the class component to a functional component
- Updates the e2e-tests for groups to work with multiple selection
- Fixes the width of the dialog
Closes #679
=> Update user selection

api/src/system/restoreBackup.ts
This PR fixes an issue with the restore backup feature that appeared since axios was updated to v0.20.0-0
=> api: Add maxBodyLength option to restore request

e2e-test/cypress/integration/backup_spec.js, e2e-test/cypress/plugins/index.js
- a backup is downloaded before all tests
- the backup is modified to save a wrong hash in the metadata file, then tested if the restore returns a "invalid backup" error. The invalid backup file is then deleted
- after all tests run, the backup that was downloaded in the beginning is restored and tested for success, then deleted
Closes #645
=> E2e-test: improve backup and restore tests

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json
=> Bump to version 1.18.0

excel-export/Dockerfile
- Avoid unwanted Node.js update which can cause errorneous beahaviour
- Some Node modules could not be prepared for recent Node.js
- Without this step Excel container would update Node.js automatically
Closes #753
=> Excel Export: Use fixed Node.js version in Docker file

doc/encryption/encryption.md
PR adds notes regarding issue #611, which is still unresolved.
=> docs: Multichain P2P encryption notes

README.md
This PR adds useful links to videos about TruBudget to the documentation. Anyone can thus gain an overview of the project, ideas behind it, and how it is used.
Closes #743
=> doc: Add links to videos about TruBudget

frontend/src/pages/Common/Permissions/PermissionSelection.js, frontend/src/pages/Common/SingleSelection.js, frontend/src/pages/Common/UserSelection.js
=> 722 - update CSS selection scroll

.github/ISSUE_TEMPLATE/1.bug.md, .github/ISSUE_TEMPLATE/1.feature.md, .github/PULL_REQUEST_TEMPLATE.md
This PR 
- adds some new todos to the PR template 
- simplifies the issue and PR templates (deletes unnecessary sections and comments)
Closes #742
=> Simplify templates, add todos to PR template

frontend/public/app.css
=> ui: update app.css prevent bg img zooming

CHANGELOG.md, api/src/index.ts, api/src/service/cache2.ts, api/src/service/document_validation.ts, api/src/service/domain/business_event.ts, api/src/service/domain/workflow/document_validate.spec.ts, api/src/service/domain/workflow/document_validate.ts, api/src/service/domain/workflow/document_validated.ts, api/src/service/domain/workflow/workflowitem_eventsourcing.ts, api/src/service/store.ts, api/src/workflowitem_validate_document.ts, frontend/src/api.js, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Common/History/HistorySearch.js, frontend/src/pages/Common/History/eventTypes.js, frontend/src/pages/Common/History/stringifyHistoryEvent.js, frontend/src/pages/Documents/DocumentOverview.js, frontend/src/pages/Documents/DocumentOverviewContainer.js, frontend/src/pages/Documents/actions.js, frontend/src/pages/Workflows/compareWorkflowItems.js, frontend/src/sagas.js
1. add a new business event workflowitem_document_validated in api
2. update stringifyHistoryEvent for document_validated event in workflowitem history
"Closes #236"
=> 236-workflowitem doc validate history

doc/installation/Developer-Setup.md, doc/tutorials/multichain-cli/multichain-cli.md
Short introduction to multichain-cli. Link in developer-setup.md not working until PR is merged. 
Closes #760
=> doc: Add multichain-cli tutorial in documentation

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json
=> bump-to-v1.19.0

api/src/lib/minio.ts
=> api: Conditionally initialize minio client

api/src/index.ts, api/src/service/document_validation.ts, api/src/service/domain/workflow/document_validate.spec.ts, api/src/service/domain/workflow/document_validate.ts, api/src/service/domain/workflow/document_validated.ts, api/src/workflowitem_validate_document.ts, blockchain/.eslintrc.yaml, blockchain/src/index.js, blockchain/src/sha256.js, blockchain/src/shell.js, frontend/package.json, provisioning/.eslintrc.yaml, provisioning/src/index.js
Sub task of "#659"
Fixes all eslint issues, so lint-ci  github job will work correctly.
=> Fix all eslint issues in all the projects

api/src/httpd/schema.ts, api/src/index.ts, api/src/network/controller/list.ts, api/src/network/controller/logNodes.ts, api/src/service/Client.h.ts, api/src/service/cache2.ts, api/src/service/domain/network/nodes_logged.ts, docker-compose/multi/multi-nodes-774.yml, scripts/multi/start-multi-774.sh
Closes #774
Multichain doesn't provide historic infromation for when was the last time node connected to network.
Functionality is built in API module and written in multichain stream. New stream "network_log" is created for this purpose, because records in "nodes" stream have a unique structure with meaning for the application. 
There are two main parts - one for setting and one for fetching data.
`checkNodes` is set to run every 24H, query TrubudgetChain about connected peers, and publish an event with currently connected node addresses and date in YYYY-MM-DD format as keys, for fast search and retrieval. 
If one of these nodes was disconnected on the next day, its address would not be used as a key in the next published record. This means that if we retrieve the latest event by node …
=> api: Add last seen to network.list API

blockchain/Dockerfile
=> Update multichain to 2.1.2

CHANGELOG.md, docker-compose/README.md, e2e-test/cypress/integration/nodes_spec.js, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Nodes/ApprovedNodesTable.js, frontend/src/pages/Nodes/ApprovedNodestableEntry.js, frontend/src/pages/Nodes/DeclinedNodesTable.js, frontend/src/pages/Nodes/Nodes.js, frontend/src/pages/Nodes/NodesTable.js, frontend/src/pages/Nodes/reducer.js
- added separate tabs for approved and declined nodes
- added expandable table row in the approved nodes table
- show connection status and last seen timestamp of each node in the approved table
- add explanation in tooltip to admin node
Closes #785 #746
=> ui: improve network table

frontend/src/sagas.js
Fix backwards compatibility issue
=> ui: hotfix in nodes fetching

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json
=> Bump to version 1.20.0

api/package-lock.json, blockchain/package-lock.json, e2e-test/cypress/integration/workflowitem_batch_spec.js, frontend/src/pages/Workflows/WorkflowItem.js, frontend/src/pages/Workflows/WorkflowList.js
=> Add e2e-test for worklfowitem badge-dialog

CHANGELOG.md, e2e-test/cypress/support/helper.js, frontend/src/currency.js, frontend/src/getExchangeRates.js
Add the currency Tunisian dinar and ethiopian birr to TruBudget
Information :
https://de.wikipedia.org/wiki/Tunesischer_Dinar
https://de.wikipedia.org/wiki/%C3%84thiopischer_Birr
Closes #806 
Closes #813
=> Add currency tunisian dinar and ethiopian birr

CHANGELOG.md, e2e-test/cypress/support/helper.js, frontend/src/currency.js
=> ui: add currency norwegian krone

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json
=> bump to v1.21.0

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification/package-lock.json, email-notification/package.json, excel-export/package-lock.json, excel-export/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v1.22.0

.github/workflows/audit/action.yml, api/package-lock.json, e2e-test/cypress/integration/workflowitem_batch_spec.js, e2e-test/cypress/support/commands.js, frontend/src/pages/Workflows/WorkflowItem.js
=> e2e-test: Add tests for batch edit

email-notification/package-lock.json, email-notification/package.json, email-notification/src/index.ts, email-notification/src/validation.ts
=> email-notification: Add Joi validation

.github/workflows/build/action.yml, .github/workflows/github-ci.yml, scripts/pipeline/publish-docker-images.sh
Trubudget's services were renamed which broke our publish docker images script.
This PR rewrites the scripts and put in some helpful comments
Tasks:
-  write a help section
-  Be able to pass project/image name and release tag
-  Add comments to script
=> Refactor publish-docker-images script

.github/CONTRIBUTING.md, blockchain/README.md, bump-tag-versions.sh, doc/Operation-Administration/Introduction.md, doc/Operation-Administration/installation/Developer-Setup.md, doc/Operation-Administration/tutorials/connect-to-network/bare-metal.md, doc/Operation-Administration/tutorials/create-new-network/bare-metal.md, docker-compose/development/docker-compose.yml, docker-compose/local/master-node.yml, docker-compose/local/slave-node.yml, docker-compose/master/master-node.yml, docker-compose/master/slave-node.yml, docker-compose/multi/docker-compose-multi-node.yml, docker-compose/testing/run-all-e2e-tests.yml, docs/developer/developer-setup.md, docs/operation-administration/installation/connect-to-existing-node/bare-metal.md, docs/operation-administration/installation/create-new-network/bare-metal.md, email-notification-service/package.json, frontend/README.md
Fixes service naming in docker-compose file
=> docker-compose: fix naming for services

frontend/src/pages/Documents/DocumentUpload.js, provisioning/src/index.js
The provisioning was faulty due to changes on the document upload in the API.
=> provisioning: fix filenames

.github/workflows/audit/action.yml, blockchain/package-lock.json, frontend/package-lock.json, provisioning/package-lock.json, storage-service/package-lock.json
Enable previously disabled audits, fix some vulnerabilities
=> Enable and fix audits

scripts/pipeline/publish-docker-images.sh
Bump to v1.23.1
- Fix docker pushes to docker hub on release event
=> Bump to v1.23.1

provisioning/src/data/prod/ecofund_call.json, provisioning/src/data/prod/ecofund_project.json, provisioning/src/data/prod/users.json, provisioning/src/data/prod/vaccine.json
- [ x I did a self review before requesting a review from another team member
=> updated demo data for prod node and users

docker-compose/development/docker-compose-slim.yml, docker-compose/development/docker-compose.yml, docker-compose/local/master-node.yml, docker-compose/local/slave-node.yml, docker-compose/master/master-node.yml, docker-compose/master/slave-node.yml, docker-compose/testing/run-all-e2e-tests.yml
=> docker-compose: use docker-volumes for blockchain

CHANGELOG.md, e2e-test/cypress/support/helper.js, frontend/src/currency.js
=> Add swiss currency

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v1.24.0

docs/developer/load-tests.md
=> doc: update min requirements for tb

CHANGELOG.md, docs/developer/documentation.md, docs/developer/load-tests.md, docs/developer/logging.mdx, e2e-test/cypress/integration/subproject_permissions_spec.js, frontend/src/helper.js, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Common/Permissions/PermissionDialog.js, frontend/src/pages/Confirmation/ActionsTable.js, frontend/src/pages/Confirmation/ConfirmationContainer.js, frontend/src/pages/Confirmation/ConfirmationDialog.js, frontend/src/pages/Confirmation/ErrorTypography.js, frontend/src/pages/Confirmation/confirmationDialogContentCreator.js, frontend/src/pages/Confirmation/createAdditionalActions.js, frontend/src/sagas.js
* Closes #907 
Fixed this issue by considering group Permissions in Confirmatino Dialog
* Closes #922
Fixed by passing permissions in revokePermission sagas, this was missing before
* Refactoring of Confirmation Dialog
Splitting huge switch into smaller functions an operation in a more functional way. Creation methods were outsourced into confirmationDialogContentCreator.js
=> 907 permissionsystem check for groups

docs/operation-administration/security.md
Added documentation related to the penetration testing of TruBudget
Closes #834
=> doc: add documentation regarding pentests

api/src/service/RpcClient.h.ts, api/src/service/RpcClient.ts
Refactor functions in RpcClient:
=> Refactor RpcClient encryption functions

scripts/development/start-dev.sh, scripts/operation/start-trubudget.sh
Use another command to fix the path within the bash scripts
=> scripts: fix path command

frontend/src/helper.js, frontend/src/pages/Workflows/WorkflowDetails.js, frontend/src/pages/Workflows/WorkflowItem.js
Fix the icon in the workflowitem-details dialog. Also replace the icon with a better one.
=> ui: fix reject-icon for workflowitems

api/src/workflowitem_view_details.ts
=> api: add rejectReason to workflowitem_view_details

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v.1.25.0

docs/developer/developer-setup.md
=> docs: reset e2e-test readme link

.github/workflows/github-ci.yml, .github/workflows/notification/action.yml
This PR resets the webhook URL and REF to the default ones since the migration on e2e-test side is done
=> Use default webhook ref/url

frontend/package.json
On Frontend startup, an info is shown about a major release in the future
=> ui: add major release info to console

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v1.26.0

.github/workflows/github-ci.yml
This PR change will trigger the release deployment whenever changes are pushed to the `1.x.x-release` branch
=> Trigger Test/Build CI on release branch push

api/package-lock.json, api/package.json, api/src/httpd/server.ts, e2e-test/cypress/integration/_System_check_spec.js
=> Fix swagger link

blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, frontend/nginx.conf, package-lock.json, package.json, storage-service/package-lock.json
Set CSP rule to allow nginx to connect to another webserver to fetch exchange rates
Setup the operation setup (because the dev setup does not use nginx) but build the frontend image local instead of fetching the image from docker-hub
=> UI: fix nginx when fetching data from outside

.github/workflows/github-ci.yml
=> 940 create more detailed log output

CHANGELOG.md, bump-tag-versions.sh, frontend/src/pages/Nodes/NodeVoting.js, logging-service/package-lock.json, logging-service/package.json
- Real fix for registering nodes in frontend
- Add change-log for logging pull request
- Fix regex in bump-to-version script
=> UI: Fix register nodes

.nsprc, .nsprc_example, CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/.nsprc, blockchain/.nsprc_example, blockchain/package-lock.json, blockchain/package.json, bump-tag-versions.sh, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v1.28.0

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v1.28.1

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, bump-tag-versions.sh, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, logging-service/package-lock.json, logging-service/package.json, package-lock.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Update dependencies, CHANGELOG.md

api/package-lock.json, api/package.json, api/src/service/Client.ts, api/src/service/RpcClient.ts, api/src/service/cache2.ts, api/src/service/document_get.ts, api/src/service/global_permission_grant.ts, api/src/service/global_permission_revoke.ts, api/src/service/global_permissions_get.ts, api/src/service/notification_list.ts, api/src/service/public_key_get.ts, api/src/service/subproject_list.ts, api/src/service/user_assignments_get.ts, api/src/service/workflowitem_permission_grant.ts, api/src/service/workflowitem_permission_revoke.ts, api/src/service/workflowitem_permissions_list.ts, api/src/system/getVersion.ts
Resolve eslint rule @typescript-eslint/return-await
If there is no try-catch block, an async function can return the
Promise directly instead of awaiting it.
See https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise
for further explanation.
=> API: Update eslint

e2e-test/package-lock.json, excel-export-service/package-lock.json, storage-service/package-lock.json
Fixed vulnerabilities that caused audits to fail
=> fix npm audits

.github/stale.yml
Raise days till stale to 60, add a comment on close & disable close when in milestone for stale bot
=> github: increase days unitl stale and add close comment for stale bot

.github/stale.yml
Same as https://github.com/openkfw/TruBudget/pull/1119 but for 2.0.0
=> Update stale bot 2.0.0

CHANGELOG.md, e2e-test/package-lock.json, e2e-test/package.json, frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/index.js, frontend/src/pages/Common/ActionButton.js, frontend/src/pages/Common/ImageSelector.js, frontend/src/pages/Common/SelectablePill.js, frontend/src/pages/Overview/BudgetsList.js, frontend/src/pages/Overview/CardView.js, frontend/src/pages/Overview/ListView.js, frontend/src/pages/Overview/Overview.js, frontend/src/pages/Overview/OverviewContainer.js, frontend/src/pages/Overview/ProjectAccordion.js, frontend/src/pages/Overview/actions.js, frontend/src/pages/Overview/reducer.js, frontend/src/pages/SubProjects/ProjectAssigneeContainer.js, frontend/src/pages/SubProjects/ProjectDetails.js, frontend/src/pages/SubProjects/reducer.js, frontend/src/sagas.js, scripts/development/start-dev.sh, scripts/operation/start-trubudget.sh
=> UI listview for 2.0.0

CHANGELOG.md, e2e-test/package-lock.json, e2e-test/package.json, frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/index.js, frontend/src/pages/Common/ActionButton.js, frontend/src/pages/Common/ImageSelector.js, frontend/src/pages/Common/SelectablePill.js, frontend/src/pages/Overview/BudgetsList.js, frontend/src/pages/Overview/CardView.js, frontend/src/pages/Overview/ListView.js, frontend/src/pages/Overview/Overview.js, frontend/src/pages/Overview/OverviewContainer.js, frontend/src/pages/Overview/ProjectAccordion.js, frontend/src/pages/Overview/actions.js, frontend/src/pages/Overview/reducer.js, frontend/src/pages/SubProjects/ProjectAssigneeContainer.js, frontend/src/pages/SubProjects/ProjectDetails.js, frontend/src/pages/SubProjects/reducer.js, frontend/src/sagas.js, scripts/development/start-dev.sh
Add ListView for projects
Update Tag component
=> UI listview

frontend/src/pages/Common/SelectablePill.js, frontend/src/pages/Overview/CardView.js, frontend/src/pages/Overview/ProjectAccordion.js
see https://github.com/openkfw/TruBudget/pull/1133
=> ui: Fix tags for 2.0.0

frontend/src/pages/Common/SelectablePill.js, frontend/src/pages/Overview/CardView.js, frontend/src/pages/Overview/ProjectAccordion.js
Fix for Tags because they are not shown correct
=> ui: Fix tags

README.md
TruBudget is a workflow engine therefore does not contain any relevant data to GDPR. If relevant data is collected, the organizations using the software have to ensure that the data is appropriately encoded or stored.
=> Add GDPR statement to root readme

.github/workflows/github-ci.yml
=> Trigger ci on 2.0.0-release push

scripts/pipeline/publish-docker-images.sh
=> Push image to private registry on 2.0.0-release push

scripts/pipeline/publish-docker-images.sh
=> Fix github action condition

api/src/project_list.ts, api/src/subproject_list.ts
remove log field from project, sub-project list endpoint
Closes #1132 
Closes #1150
=> api: remove log field from project/subproject list

api/src/httpd/router.ts, api/src/httpd/schema.ts, blockchain/src/index.js, blockchain/src/readiness.js, e2e-test/cypress/integration/subproject_permissions_spec.js, e2e-test/cypress/plugins/index.js, email-notification-service/README.md, email-notification-service/src/db.ts, email-notification-service/src/index.ts, excel-export-service/README.md, excel-export-service/package-lock.json, excel-export-service/src/api.ts, excel-export-service/src/index.ts, frontend/src/pages/Overview/ProjectPermissionsContainer.js, frontend/src/pages/SubProjects/SubprojectPermissionsContainer.js, frontend/src/pages/Workflows/WorkflowDialog.js, provisioning/src/api.js, provisioning/src/index.js, storage-service/README.md, storage-service/package-lock.json, storage-service/package.json, storage-service/src/index.ts, storage-service/src/minio.ts
Add /readiness and /liveness to all services
Readiness: Checks if services are available, everything correct started 
> Check dependent services 
Liveness: checks if there is no hang up. 
> Just return 200 
> Maybe return Uptime: process.uptime()
Closes #1122 
Closes #1121
=> Add /readiness and /liveness to all services

api/src/httpd/router.ts, provisioning/src/api.js, provisioning/src/index.js, provisioning/src/lib.js
=> Api readiness improvement

frontend/configureServer.sh
Reverts openkfw/TruBudget#1179
=> Revert "docs: Add closing slash to br tags"

excel-export-service/src/index.ts
=> excel-export: Fix readiness endpoint

.github/workflows/audit/action.yml, .github/workflows/danger/action.yml, .github/workflows/github-ci.yml, .github/workflows/lint/action.yml, .github/workflows/test/action.yml, .github/workflows/update-documentation.yml
npm install is creating package-lock.json but we need to install packages depending on the package-lock.json so npm ci is the way to go
=> Use npm ci and legacy-peer-deps for frontend installs

blockchain/src/connectToChain.js
Add logs to blockchain to better describe the connection and approval process of a beta node.
=> bc: Add additional logs to conenction process

CHANGELOG.md, api/src/lib/joiValidation.ts, docs/operation-administration/installation/create-a-new-network/bare-metal.md, logging-service/package-lock.json, logging-service/package.json
Change ascii regexp to Unicode RegExp using xregexp since joi doesn't support unicode properties like pL/p{Letter}
Closes #1202
=> use unicode regexp for validation schemas

api/package-lock.json, api/package.json, api/src/lib/htmlSanitize.ts, api/src/lib/joiValidation.spec.ts, api/src/lib/joiValidation.ts
=> api: add unicode regex and html-strip for safe string schema

frontend/src/pages/Workflows/WorkflowItem.js
Alignment of workflowitem checkboxes for a better user view (css modified).
Closes #1200
=> ui: Align workflowitem checkboxes

blockchain/src/index.js
Fix exit statement in blockchain. This fixes start-dev.sh setup.
=> blockchain: fix exit statement

provisioning/package-lock.json, provisioning/package.json
=> Update provisiong npm packages

frontend/src/pages/Workflows/WorkflowDialog.js
- [] The E2E tests are passing
=> 1110 workflowdialog edit

storage-service/.eslintrc.yaml, storage-service/package-lock.json, storage-service/package.json, storage-service/src/minio.ts
Update all npm packages to newest
Implement breaking changes
Repair eslint setup
Closes parts of https://github.com/openkfw/TruBudget/issues/1089
=> Update storage-service npm packages

excel-export-service/.eslintrc.yaml, excel-export-service/package-lock.json, excel-export-service/package.json, excel-export-service/src/api.ts, excel-export-service/src/index.ts
Update all npm packages to newest
Implement breaking changes
Closes parts of #1089
=> Update excel-service npm packages

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, bump-tag-versions.sh, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v2.1.0

CHANGELOG.md, blockchain/src/index.js, docker-compose/README.md, docker-compose/blockchain/docker-compose.alphanode.yml, docker-compose/e2e-test/docker-compose.yml, docker-compose/e2e-test/local-build.docker-compose.yml
- Add e2e-test docker-compose files
- Fix blockchain alpha node docker-compose file configuration
- Fix blockchain autostart condition on restoreBackup
#1263 
Closes #1285
=> Add e2e-test docker-compose

CHANGELOG.md, e2e-test/cypress/integration/login_spec.js, frontend/src/pages/Common/Password.js
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/CONTRIBUTING.md).
- [ x] I fixed all necessary PR warnings
- [x ] The commit history is clean
=> 1225 include password display option

frontend/src/pages/Navbar/NotificationIcon.js
=> ui: fix overflow in notification count

blockchain/src/index.js
This PR increases the timeout of the backup requests, download & restore.
If not increased large backups cannot be downloaded or restored.
=> bc: Increase request timeout of backup endpoints

api/package-lock.json, docs/developer/developer-setup.md
=> doc:Update dev setup

scripts/development/start-dev.sh
=> Add a command check for the compatibility with newer versions of docker

docs/developer/developer-setup.md, docs/user-guide/README.md, scripts/development/README.md, scripts/operation/README.md
Updated documentation to include infos regarding default credentials for TruBudget (root credentials)
Closes #1318
=> Document default credentials for local start

frontend/src/api.js, frontend/src/config.js, frontend/src/logging/logger.js, frontend/src/pages/Login/LoginPageContainer.js, frontend/src/sagas.js, frontend/src/store.js
=> Frontend environment variable configuration

CHANGELOG.md, api/src/service/domain/workflow/workflowitem_create.ts
=> Add default exchange rate of 1.0

CHANGELOG.md, api/package-lock.json, e2e-test/cypress/integration/workflowitem_reject_spec.js, frontend/.nsprc, frontend/package-lock.json, frontend/package.json, frontend/src/sagas.js
Added a check for rejected workflow items before calculating the assigned budget for project and subproject detail views.
Closes #1275
=> Exclude rejected WFI from assigned budget

frontend/package-lock.json, frontend/package.json, frontend/src/pages/Overview/reducer.js, frontend/src/pages/SubProjects/reducer.js
=> ui: 1362 immutablejs upgrade

e2e-test/cypress/integration/project_assignee_spec.js, e2e-test/cypress/integration/subproject_permissions_spec.js, frontend/src/pages/SubProjects/SubProjectTable.js, frontend/src/pages/Workflows/WorkflowContainer.js, frontend/src/pages/Workflows/WorkflowDetails.js, frontend/src/pages/Workflows/WorkflowItem.js, frontend/src/sagas.js
=> UI: Workflow Buttons

frontend/src/logging/logger.js
=> ui: fix logging

e2e-test/cypress/integration/project_assignee_spec.js, frontend/src/pages/Workflows/WorkflowItem.js, frontend/src/pages/Workflows/WorkflowList.js
=> UI: Workflowitem drag and drop styling

.vscode/launch.json, api/package.json, scripts/development/docker-compose.yml
=> API: Fix attach debugger

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v2.2.0

.nsprc, api/.nsprc, api/package-lock.json, api/package.json, blockchain/.nsprc, email-notification-service/.nsprc, excel-export-service/.nsprc, frontend/src/getExchangeRates.js, logging-service/package-lock.json, logging-service/package.json, provisioning/.nsprc, storage-service/.nsprc
=> Update packages with "semver" dependency

frontend/environment-variables.md, frontend/src/config.js, frontend/src/getExchangeRates.js
=> ui: update URL for fetching exchange rates

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v2.2.1

excel-export-service/src/index.ts
=> excel-export: fix unhandled promise rejection when api not reachable

.github/workflows/update-documentation.yml
Bumping node-version: from "12.x" to "16.x" fixed the error.
Closes #1398
=> github-actions: fix copy job

api/package-lock.json, blockchain/package-lock.json, blockchain/package.json, logging-service/package-lock.json, scripts/operation/README.md, scripts/operation/docker-compose.provision.yml, scripts/operation/start-provision.sh
=> scripts: provisioning script

frontend/src/pages/Overview/OverviewContainer.js, frontend/src/pages/Overview/actions.js, frontend/src/pages/Overview/reducer.js, frontend/src/sagas.js
=> ui: enable live update of projects overview

blockchain/.nsprc, blockchain/package-lock.json, blockchain/package.json
=> blockchain: fix npm vulnerability

e2e-test/.gitignore, e2e-test/README.md, e2e-test/cypress.json, e2e-test/cypress/plugins/index.js, e2e-test/cypress/support/index.js, e2e-test/package-lock.json, e2e-test/package.json
=> Create html report after e2e are run

.github/SUPPORT.yml
Closes #1443 broken document link issue
=> fixed documentation link

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v2.3.0

storage-service/.nsprc, storage-service/package-lock.json, storage-service/package.json
=> storage-service: fix audit

frontend/src/pages/Overview/Overview.js
=> ui: toggle project  view button

CHANGELOG.md, provisioning/README.md, provisioning/src/data/prod/groups.json, provisioning/src/data/prod/users.json, provisioning/src/data/test/groups.json, provisioning/src/data/test/users.json, provisioning/src/users_and_groups.js
Feature: adding dynamic permissions to users in provisioning
Closes #1499
=> Provisioning: Dynamic user permissions

.vscode/settings.json, CHANGELOG.md, frontend/.eslintrc, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Common/DatePicker.js, frontend/src/pages/Common/Identifier.js, frontend/src/pages/Confirmation/ConfirmationContainer.js, frontend/src/pages/Confirmation/confirmationDialogCreator.js, frontend/src/pages/Workflows/WorkflowDialog.js, frontend/src/pages/Workflows/WorkflowDialogAmount.js, frontend/src/pages/Workflows/WorkflowDialogContainer.js, frontend/src/pages/Workflows/WorkflowDialogContent.js, frontend/src/pages/Workflows/actions.js, frontend/src/pages/Workflows/reducer.js, frontend/src/pages/Workflows/templates/monitoring.json, frontend/src/pages/Workflows/templates/payments.json, frontend/src/pages/Workflows/templates/tender.json, frontend/src/pages/Workflows/templates/workflowTemplates.js, frontend/src/sagas.js
=> 1430 workflow template

api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/Dockerfile, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, logging-service/package-lock.json, logging-service/package.json, migration/package-lock.json, migration/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
Updated e2e docker image because node 10 couldn't load updated axios. Maybe importing cjs directly would work. But if 18 passes, I don't see any downside to it.
Closes #1525
=> ‼️HIGH PRIORITY: Upgrade axios version to mitigate vulnerability

api/package-lock.json, api/package.json
=> Add @types/react as dev dependency

e2e-test/cypress/integration/backup_spec.js
=> Fix Backup tests (E2E)

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Bump to v2.5.0

CHANGELOG.md, frontend/src/pages/Login/LoginPage.js, frontend/src/pages/Login/LoginPageContainer.js, frontend/src/pages/Login/actions.js, frontend/src/pages/Login/reducer.js
=> frontend: add loading indicator on proxy login

logging-service/Dockerfile, logging-service/index.js, logging-service/package-lock.json, logging-service/package.json, logging-service/serve.js
=> updated deprecated dep versions

api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, logging-service/index.js, logging-service/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> update logging-service version in services

docs/operation-administration/installation/connect-to-an-existing-network/docker.md
=> Doc: Connecting to existing network

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, bump-tag-versions.sh, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> Release 2.6.0

.github/workflows/github-ci.yml
=> updated checkout and setup-node to latest versions

.github/workflows/codeql.yml
=> CI: Add github code security scan

.github/workflows/daily-security-check.yml
Previous issue is already closed. This is a tiny modification.
=> ci:added frontend collector to the scan list

.github/actions/audit-report-action/issue.js
Fixed the problem where the bot would create new issue despite having no vulnerability.
=> Bugfix Github Action Bot

.github/workflows/test/action.yml, api/Dockerfile, blockchain/Dockerfile, email-notification-service/Dockerfile, excel-export-service/Dockerfile, frontend-collector/Dockerfile, frontend/Dockerfile, frontend/Dockerfile.dev, migration/Dockerfile, provisioning/Dockerfile, storage-service/Dockerfile
=> all: update dockerfiles

.github/actions/audit-report-action/docker.js
=> Scan images with main tag

.github/actions/audit-report-action/dist/index.js, e2e-test/Dockerfile, frontend/Dockerfile
=> Image vulnerabilities fix

api/.eslintrc, api/src/service/domain/workflow/subproject_create.ts, api/src/service/domain/workflow/workflowitem_create.ts, api/src/service/subproject_create.ts, api/src/service/workflowitem_create.ts, api/src/subproject_create.ts, api/src/workflowitem_create.ts
=> api: subproject and workflowitems inherit project permissions

.github/actions/audit-report-action/action.yml, .github/actions/audit-report-action/audit_report_action.md, .github/actions/audit-report-action/dist/licenses.txt, .github/workflows/daily-security-check.yml
=> github actions: update audit-report-action

api/src/lib/joiValidation.ts, api/src/service/domain/organization/user_record.ts
=> api:Increase length of user ID

frontend/src/pages/Common/Searchbar.js, frontend/src/pages/Overview/TableView.js
=> ui: show "delete search term" button

frontend/src/pages/Workflows/WorkflowItem.js
=> ui: error at workflow screen

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v2.7.0

.github/workflows/build/action.yml, .github/workflows/update-documentation.yml
=> ci: update set-output

e2e-test/cypress/integration/workflowitem_edit_spec.js, e2e-test/cypress/integration/workflowitem_history_spec.js
=> e2e: fix failing tests

frontend/package-lock.json, frontend/package.json, frontend/src/pages/Confirmation/validation.js, frontend/src/pages/Documents/DocumentUpload.js
- refactor validation file on frontend to remove @hapi/joi and replace it with Yup validation library
Closes #1673
=> frontend: unify validation libraries

blockchain/package-lock.json, blockchain/package.json
=> blockchain: fix audit

e2e-test/cypress/integration/users_spec.js, frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Users/UserDialogContent.js
- Add more descriptive validation messages in Create user form
- new messages are related to Account name and Login ID fields
- Add e2e tests on behalf of new validation messages
"Closes #1704 "
=> Frontend descriptive validation messages

frontend/src/pages/Common/TagEditor.js
=> ui: increase max length of tag

api/src/service/domain/document/workflowitem_document_delete.ts, frontend/src/pages/Documents/DocumentOverview.js, frontend/src/pages/Documents/DocumentUpload.js
Closes #1663 
Also fixes some validateDOMNesting errors.
=> 1663 delete url document

.github/ISSUE_TEMPLATE/1.bug.md, .github/PULL_REQUEST_TEMPLATE.md
=> Improve bug and PR template text

e2e-test/cypress/integration/workflowitem_batch_spec.js, frontend/src/pages/Workflows/WorkflowEditDrawer.js, frontend/src/pages/Workflows/WorkflowTable.js
1. Run e2e tests for workfloitems_batch
=> 1699 frontend,e2e-test:Fix e2e tests with batch actions

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v2.9.0

blockchain/package-lock.json, blockchain/package.json, e2e-test/Dockerfile, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, storage-service/package-lock.json, storage-service/package.json
=> multiple: patch vulnerability

blockchain/.nsprc, blockchain/package-lock.json, blockchain/package.json
npm audit, pipeline pass
Closes #1767
=> blockchain: patch lib vulnerability

frontend/src/pages/Overview/CardView.scss
- custom pagination action buttons for better readability in the app
4. ...
Closes #1773
=> 1773 Pagination action buttons custom design

api/src/project_list.v2.ts, e2e-test/cypress/integration/currencies_spec.js, e2e-test/cypress/integration/project_budget_spec.js, e2e-test/cypress/integration/project_edit_spec.js, e2e-test/cypress/integration/project_history_spec.js, e2e-test/cypress/support/commands.js, frontend/src/localStorage.js, frontend/src/pages/Overview/CardView.js
e2e tests on pipeline should pass
Closes #1775
=> frontend: persist pagination and fix tests

e2e-test/Dockerfile
=> e2e: upgrade base image

scripts/development/docker-compose.yml, storage-service/src/azureblob.ts, storage-service/src/storage.ts
1. Start dev environemnt with --slim option
2. It should start and work
=> scripts:Remove unnecessary dependency

frontend/src/pages/Main/Main.js, frontend/src/pages/Navbar/Breadcrumbs.js, frontend/src/pages/Navbar/Breadcrumbs.scss, frontend/src/pages/Nodes/NodeVoting.scss, frontend/src/pages/index.scss
- fix breadcrumbs position so it is aligned across all screen sizes with main content
2. open developer tools and play around with resolution of the app
3. breadcrumbs position should be aligned with main content at all times
Closes #1786
=> 1786 fix breadcrumbs position

blockchain/src/index.js, excel-export-service/Dockerfile, excel-export-service/src/index.ts, scripts/development/start-dev.sh
=> various small fixes

scripts/development/README.md, scripts/development/start-dev.sh
1. As a developer start envronment
2. Use `--build-only` option with start script
3. Environment should start and selected services should be rebuiled
4. ...
Closes #1793
=> 1793 Build only selected services with dev startscript

scripts/development/docker-compose.yml, scripts/operation/docker-compose.provision.yml, scripts/operation/docker-compose.yml, storage-service/environment-variables.md, storage-service/package-lock.json, storage-service/package.json, storage-service/src/config.ts, storage-service/src/index.ts
0. full deployment
1. set RATE_LIMIT env var to low value
2. try to flood storage-service with requests
Closes #1784
=> 1784 storage-service rate limit

generate-latest-changelog.js
1. run e.g. `npm run generate-changelog 2.10.0`
2. Validate if changelog is correctly updated
=> Fix changelog links and harcoded version

e2e-test/cypress/integration/project_analytics_spec.js, e2e-test/cypress/integration/project_assignee_spec.js, e2e-test/cypress/integration/subproject_analytics_spec.js
=> e2e: fix failing

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v2.10.0

frontend/src/themes/theme.js
- time to open dropdown/select reduced across the app
2. go to project details and open perhaps assignee dropdown
3. click on Details button and then open currency dropdown
4. in both cases, time to open dropdown should be reduced
Closes #1812
=> 1812 Dropdown/Select open time reduced

api/src/service/cache2.ts
Couldn't reproduce the underlying condition. Just check that TB works and performs well.
Closes #1845
=> api: improve cache lock implementation

api/.nsprc, api/package-lock.json, blockchain/package-lock.json, e2e-test/package-lock.json, email-notification-service/package-lock.json, excel-export-service/package-lock.json, frontend-collector/package-lock.json, frontend/package-lock.json, logging-service/package-lock.json, provisioning/package-lock.json, storage-service/package-lock.json
Fix npm audit warnings
1. Everything is working
=> Update package-lock with npm audit fix

.github/workflows/daily-security-check.yml
=> gh-actions: Update scanned releases

README.md, docs/operation-administration/first-steps-checklist.md
=> Fixed Typo in installation instructions

api/package-lock.json, frontend/Dockerfile, storage-service/package-lock.json, storage-service/package.json, storage-service/src/minio.ts, storage-service/src/storage.ts
=> 1925 upgrade libs

e2e-test/cypress/integration/documents_spec.js
=> e2e: fix documents spec

e2e-test/cypress/integration/project_analytics_spec.js, e2e-test/package-lock.json, e2e-test/package.json
=> e2e: fix some tests still failing on pipeline

frontend/Dockerfile
=> frontend:Upgrade nginx image

api/src/config.ts
1. Change db name `API_DB_DATABASE` env variable
2. Check if correct database is used
Closes #1959
=> 1959 Fix variable name

frontend/src/pages/Overview/ProjectDialog.js
* fixed edit project photo upload
1. log in
2. edit existing project and upload some new photo
3. on submit new project picture should be saved and displayed 
Closes #1954
=> #1954-edit project photo upload

api/src/app_latest_version.ts, blockchain/package-lock.json, blockchain/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, storage-service/package-lock.json, storage-service/package.json
1. Start app
2. Check if pipeline is passing
=> Fix absolute import to relative

scripts/development/docker-compose.minio.yml
1. Start full dev app
2. Check if you can login on localhost:9001 with minio, minio123 credentials
Closes #1950
=> 1950 Add port for local browsing of minio files

api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, provisioning/package-lock.json, provisioning/package.json
=> multiple: patch vulnerable library

frontend/configureServer.sh, frontend/nginx.conf
1. Check if app is runnig
Closes #1984
=> frontend:Add nginx buffer config

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v2.15.0

frontend/package-lock.json, frontend/package.json, frontend/src/pages/Loading/withInitialLoading.js, frontend/src/pages/Overview/CardView.js, frontend/src/pages/SubProjects/SubProjectTable.js
1. Rebuild frontend image and run TB
2. There should be no warning nor error concerning findDOMNode, property f, button outside span
Closes #1989
=> frontend: fixed console warnings

api/.eslintrc, e2e-test/cypress/integration/project_edit_spec.js, e2e-test/cypress/support/commands.js, provisioning/src/index.js
=> provisioning: In case of failure, retry before quitting

frontend/src/pages/Status/StatusContainer.js
1. Open Service status screen
2. Developer tools > network you should see request being made
Closes #1975
=> ui: check service at regular intervals

frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js
=> ui: orga info string

api/src/envVarsSchema.ts, api/src/user_forgot_password.ts
* fixed api joi schema validation, app should start properly now
1. start app with --full --build and should start properly now
=> fixed api joi schema validation

CHANGELOG.md, api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, e2e-test/package-lock.json, e2e-test/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, frontend/package-lock.json, frontend/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> bump to v2.16.0

frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js
- change of wording for #1875
4. ...
Closes #1875
=> 1875 amount to financing amount

api/package-lock.json, api/package.json, blockchain/package-lock.json, blockchain/package.json, email-notification-service/package-lock.json, email-notification-service/package.json, excel-export-service/package-lock.json, excel-export-service/package.json, frontend-collector/package-lock.json, frontend-collector/package.json, frontend/package-lock.json, frontend/package.json, logging-service/package-lock.json, migration/package-lock.json, migration/package.json, provisioning/package-lock.json, provisioning/package.json, storage-service/package-lock.json, storage-service/package.json
=> patched vulnerable libraries

frontend/src/pages/Documents/DocumentUpload.js, frontend/src/pages/Documents/DocumentUpload.scss, frontend/src/pages/Workflows/WorkflowDialog.js, frontend/src/pages/Workflows/WorkflowDialogContainer.js, frontend/src/pages/Workflows/actions.js, frontend/src/pages/Workflows/reducer.js
- see #2018 
4. ...
Closes #2018
=> 2018: Add remove button for DocumentUpload

email-notification-service/src/index.ts, email-notification-service/src/sendMail.ts, email-notification-service/src/util.ts
=> email-service: transporter without auth

blockchain/package-lock.json, blockchain/package.json
=> blockchain: patch jsonpath-plus

e2e-test/Dockerfile, e2e-test/package-lock.json, e2e-test/package.json
=> e2e-test: update cypress

frontend/src/pages/SubProjects/SubProjectDialogContent.js
- see #2032 
1. login as user
2. try to create new subproject
3. You should not see error in console
Closes #2032
=> 2032: Fix subproject warning

frontend/src/pages/Common/SelectablePill.js
- see #2042 
4. ...
Closes #2042
=> 2042: Fix nested div warning in console

frontend/src/pages/Common/UserPassword.js, frontend/src/pages/Users/UserDialogContent.js
=> 2034 UI: Fix password input

frontend/src/pages/Overview/actions.js, frontend/src/pages/Overview/reducer.js, frontend/src/pages/Workflows/WorkflowBatchEditContainer.js, frontend/src/pages/Workflows/WorkflowEditDrawer.js, frontend/src/sagas.js
1. Create more then 10 projects
2. Create sub projects at at least 2 of them on different pagination page (e.g. 1st and 11th project)
3. Create workflow action(s) in one of them
4. Try to copy workflow actions
5. It should work -> You should see all projects in the dropdown
Closes #1944
=> #1944 List all projects when copying workflow actions

blockchain/src/envVarsSchema.js, email-notification-service/src/envVarsSchema.ts
=> email validation

email-notification-service/src/envVarsSchema.ts
=> optional is a joke

excel-export-service/src/envVarsSchema.ts
=> excel-exprt: allow empty vars

storage-service/src/envVarsSchema.ts
=> storage-service: allow-empty-vars

frontend/package-lock.json, frontend/package.json
* cleaned up package overrides
1. click through application to check that everything works
Closes #2017
=> cleaned up package overrides

blockchain/src/envVarsSchema.js, blockchain/src/multichain-feed/email-notifications/createAuthToken.js, blockchain/src/multichain-feed/email-notifications/sendNotifications.js, email-notification-service/src/middleware.ts
=> 2087 Fix error handling between blockchain and email service

blockchain/package-lock.json, blockchain/package.json
=> Patch critical vulnerability

.github/workflows/daily-security-check.yml, api/package-lock.json, api/package.json, migration/package-lock.json, migration/package.json
=> ci: Bump audit versions

frontend/src/languages/english.js, frontend/src/languages/french.js, frontend/src/languages/georgian.js, frontend/src/languages/german.js, frontend/src/languages/portuguese.js, frontend/src/pages/Common/CreateButton.js, frontend/src/pages/Main/Main.scss, frontend/src/pages/Overview/CardView.js, frontend/src/pages/Overview/CardView.scss, frontend/src/pages/Overview/TableView.js, frontend/src/pages/Overview/TableView.scss, frontend/src/pages/SubProjects/SubProjectContainer.js, frontend/src/pages/SubProjects/SubProjectContainer.scss, frontend/src/pages/SubProjects/SubProjects.js, frontend/src/pages/SubProjects/SubProjects.scss, frontend/src/pages/Users/Users.js, frontend/src/pages/Workflows/Workflow.js, frontend/src/pages/Workflows/Workflow.scss, frontend/src/pages/Workflows/WorkflowContainer.js, frontend/src/pages/Workflows/WorkflowContainer.scss
- see #2107 
1. Login as user
2. Go to Users tab and change between Users and Group in the table - on top right there should be Add button with text now
3. Go to projects - on top right there should be Add button with text now
4. Go to subprojects - on top right there should be Add button with text now
5. Go to workflow actions - on top right there should be Add button with text now
Closes #2107
=> 2107: More descriptive Add buttons

api/package-lock.json, blockchain/package-lock.json, e2e-test/package-lock.json, email-notification-service/package-lock.json, excel-export-service/package-lock.json, frontend/package-lock.json, storage-service/package-lock.json
* fixed vulnerable npm packages
=> npm vulnerabilities fix

frontend/src/pages/Main/TourWrapper.scss
1. Start tour and check it's visual
=> frontend:Change styles to rem
