- api/src/service/cache2.ts
- api/src/service/domain/workflow/project_assign.ts
- api/src/service/domain/workflow/project_close.ts
- api/src/service/domain/workflow/project_eventsourcing.ts
- api/src/service/domain/workflow/project_permission_grant.ts
- api/src/service/domain/workflow/project_permission_revoke.ts
- api/src/service/domain/workflow/project_projected_budget_update.ts
- api/src/service/domain/workflow/project_updated.ts
- api/src/service/domain/workflow/subproject_assign.ts
- api/src/service/domain/workflow/subproject_close.ts
- api/src/service/domain/workflow/subproject_eventsourcing.ts
- api/src/service/domain/workflow/subproject_items_reorder.ts
- api/src/service/domain/workflow/subproject_permission_grant.ts
- api/src/service/domain/workflow/subproject_permission_revoke.ts
- api/src/service/domain/workflow/subproject_projected_budget_delete.ts
- api/src/service/domain/workflow/subproject_update.ts
- api/src/service/domain/workflow/subproject_updated.ts
- api/src/service/domain/workflow/workflowitem_assign.ts
- api/src/service/domain/workflow/workflowitem_close.ts
- api/src/service/domain/workflow/workflowitem_eventsourcing.ts
- api/src/service/domain/workflow/workflowitem_permission_grant.ts
- api/src/service/domain/workflow/workflowitem_permission_granted.ts
- api/src/service/domain/workflow/workflowitem_permission_revoke.ts
- api/src/service/domain/workflow/workflowitem_update.spec.ts
- api/src/service/domain/workflow/workflowitem_update.ts
- api/src/service/domain/workflow/workflowitem_updated.ts
Fixes #162 and #161 
The cache now always returns a copy of its data. This might reduce performance a bit, but ensures that nobody can edit the cache.
Additionally when the creation logic of the domain calls the "apply" function, it will always use a copy of the datasource.
> Cache immutability

- api/src/lib/symmetricCrypto.spec.ts
- api/src/lib/symmetricCrypto.ts
- api/src/organization/organization.ts
- api/src/service/user_authenticate.ts
- api/src/user_authenticate.ts
Closes #174.
1. Start blockchain
1. Start API with `ORGANIZATION=A` and `ORGANIZATION_VAULT_SECRET=a`
1. Run provisioning
1. Restart API with `ORGANIZATION=B` and `ORGANIZATION_VAULT_SECRET=b`
1. Run frontend
1. Log in with `mstein` and `test`
On the UI you should see "Incorrect password" and the logs should show this:
```plain
msg: "authentication failed: failed to decrypt the user's private key with the given organization secret (does the user mstein belong to organization ACMECorp2?): decryption failed"
error: {
...
}
```
> api: Improve handling of privkey decryption errors

- frontend/src/sagas.js
When a user logs in with invalid credentials, the HTTP error code is now
400. Since it was 401 before, the snackbar after successful login did
not behave correctly.
Added error code 400 to snackbar message configuration.
> ui: Add new error code for failed login to saga

- api/src/subproject_list.ts
This is to fix the bug where 'additionalData' is not returned when
calling 'subproject_list'.
The solution is to add the 'additionalProperties: true' to the Swagger
schema which enables the display of JSON like data in the response.
Closes #214
> api: Add 'additionalProperties' to subproject_list

- CHANGELOG.md
- api/src/service/domain/workflow/money.ts
- api/src/service/domain/workflow/workflowitem.ts
- api/src/service/domain/workflow/workflowitem_updated.ts
- api/src/workflowitem_create.ts
- provisioning/src/data/prod/gavi.json
- provisioning/src/data/test/multiple_donors_2.json
Only allow the point character as the decimal sign for a workflowitems' amount and exchangeRate fields. While we generally try to avoid interpreting amounts, this change is important to ensure that values on the chain can be read without knowing the author's locale settings.
Closes #216 
- checkout acbdd13
- run provisioning => it should fail now, as it includes decimal commas in some exchangeRate fields
- forward to e43e70b
- run provisioning again => should work now, as the fields are fixed in the provisioning data
> Only allow point as decimal sign for amount and exchangeRate

- e2e-test/package-lock.json
- e2e-test/package.json
- excel-export/package-lock.json
- excel-export/package.json
- npmversion.sh
- provisioning/package-lock.json
- provisioning/package.json
It has proven a bit tedious to update package versions when cutting a release. This PR introduces a small script that uses `npm version` to update those versions, providing the same "API" while applying the change to all `package.json` (and related) files.
@gonzochic @Stezido @mathiashoeld Thoughts? Suggestions?
For example, for the upcoming release we could use either one of those:
```bash
./npmversion.sh 1.0.0-beta.10
```
```bash
./npmversion.sh prerelease
```
Simply run `./npmversion.sh` without arguments to see the usage help (copied mostly from `npm version`).
> Sync version bump

- frontend/src/pages/SubProjects/SubprojectDialog.js
When creating a new subproject the submit button is now active as soon
as description and currency are available.
Create a new subproject, add name and currency, but no projected budget -> The submit button should be active.
> ui: Make subproject projected budget not mandatory

- CHANGELOG.md
- api/src/httpd/router.ts
- api/src/httpd/schema.ts
- api/src/index.ts
- api/src/service/cache2.ts
- api/src/system/restoreBackup.ts
Enabling strict schema validation broke the restore feature, because fastify-swagger doesn't support the required type "string" with format "binary". Furthermore, the newly introduced caching required restarting the API after restoring a backup.
This PR fixes that by:
- using AnyValue as the body schema type
- apply cache invalidation after restore (or restore attempt)
Closes #237 
happy path:
- log in as root
- open the hamburger menu and download a backup
- change things (edit a project or add a new project)
- open the hamburger menu and restore the backup
- log in again and verify that the data has been reset
unhappy path:
- try to upload something else, like a non-gzip file or a gzip files that contains other things (I haven't tested the latter, actually)
> Fix backup/restore feature

- CHANGELOG.md
- frontend/src/pages/Common/CreationDialog.js
**Problem**:
If the screen is too small the action buttons of the creation dialog are not accessible.
**Solution**:
Make the dialog scrollable .
Closes #240
> UI: make creation dialog responsive

- CHANGELOG.md
- api/src/authz/intents.ts
- api/src/index.ts
- api/src/project_view_history_v2.ts
- api/src/service/project_trace_events.ts
- api/src/service/subproject_trace_events.ts
- api/src/service/workflowitem_trace_events.ts
- api/src/subproject_view_history.ts
- api/src/subproject_view_history_v2.ts
- api/src/workflowitem_view_history.ts
The new endpoints return only the history for the selected project, subproject
or workflowitem. Previously, a subproject's history would also contain the
workflowitems' history elements.
Co-authored-by: Mathias Höld <mathias.hoeld@accenture.com>
Related to #252
> api: New endpoints for project/subproject/workflowitem history

- CHANGELOG.md
- frontend/src/languages/english.js
- frontend/src/languages/french.js
- frontend/src/languages/german.js
- frontend/src/languages/portuguese.js
- frontend/src/pages/Common/History/ScrollingHistory.js
- frontend/src/pages/Common/HistoryList.js
- frontend/src/pages/Notifications/actions.js
- frontend/src/pages/SubProjects/ProjectHistoryDrawer.js
- frontend/src/pages/SubProjects/SubProjectContainer.js
- frontend/src/pages/SubProjects/SubProjects.js
- frontend/src/pages/SubProjects/SubprojectHistoryDrawer.js
- frontend/src/pages/SubProjects/actions.js
- frontend/src/pages/SubProjects/reducer.js
- frontend/src/pages/WorkflowitemDetails/WorkflowHistoryTab.js
- frontend/src/pages/WorkflowitemDetails/actions.js
- frontend/src/pages/WorkflowitemDetails/reducer.js
- frontend/src/pages/Workflows/Workflow.js
- frontend/src/pages/Workflows/WorkflowContainer.js
- frontend/src/pages/Workflows/WorkflowDetails.js
- frontend/src/pages/Workflows/actions.js
- frontend/src/pages/Workflows/reducer.js
- frontend/src/sagas.js
The project/subproject/workflowitem history uses infinite scrolling.
Before this commit: When the last page is reached, the limit was not adjusted which lead to
overfetching.
Now: The limit is calculated based on the offsetIndex. If it is 0 (i.e.
the last page is reached), the limit is set to the modulus of the number
of events and the limit, which leaves only the events that were not
fetched before.
This also fixes the problem where the history drawer was populated with the wrong items after closing.
* Added stringify entries for update and delete projected budgets
* Fixed stringify of permission related history entries. The "formatPermission" method was restored to translate the permissions from the event to a value that can be read from the language files.
Closes #275 
Closes #279 …
> Fix fetching of history items and bug fixes

- CHANGELOG.md
- frontend/src/pages/Common/HistoryList.js
- frontend/src/pages/SubProjects/reducer.js
- frontend/src/pages/Workflows/reducer.js
'No event' is displayed only if there are no elements returned from the
API. This is achieved by only displaying the element if the loading
process is finished.
Closes #294
> ui: Fix display of 'No event' in history

- dangerfile.js
Danger warns about missing E2E-tests for the following conditions:
- There are changes in the frontend
- AND there are no changes in the e2e tests
- AND the pull request is not marked as trivial
Closes #256
> danger: Add check for missing e2e-tests

- CHANGELOG.md
- frontend/src/pages/Workflows/WorkflowItem.js
When a workflow item is updated via the API from amount type "N/A" to
"disbursed" or "allocated", the exchange rate does not need to be set
immediately (it is only needed if the workflowitem is closed). Therefore
it can happen that no exchange rate (or amount is set).
If no amount or exchange rate is set, the amount field is left blank.
Closes #297
> ui: Don't display amount if no exchange rate is set

- CHANGELOG.md
- api/src/authz/intents.ts
- api/src/index.ts
- api/src/service/cache2.ts
- api/src/service/domain/business_event.ts
- api/src/service/domain/organization/user_create.ts
- api/src/service/domain/organization/user_created.ts
- api/src/service/domain/organization/user_eventsourcing.ts
- api/src/service/domain/organization/user_password_change.spec.ts
- api/src/service/domain/organization/user_password_change.ts
- api/src/service/domain/organization/user_password_changed.ts
- api/src/service/domain/organization/user_record.ts
- api/src/service/project_update.ts
- api/src/service/store.ts
- api/src/service/user_create.ts
- api/src/service/user_password_change.ts
- api/src/user_password_change.ts
A new API endpoint was added that enables the change of a user's
password. For this, the following has been added:
* New intent 'user.changePassword'
* This new intent is given to every user per default so every user can change his/her own password
* New HTTP endpoint 'user.changePassword'
* New service
* New business event 'UserPasswordChanged'
* New unit test
* New business logic 'user_password_change'
* New event 'user_password_changed'
To be consistent with the rest of the API, the files for user handling
(creating, getting, sourcing) have been refactored.
Relates to #79 
Call the API endpoint `user.changePassword` with `userId` and a new password and try authenticating the user using the old password (should not be possible) and then the new password (should be possible).
> api: Add endpoint to change a user's password

- dangerfile.js
To correctly check for missing E2E-tests, the file path has been
modified to correctly include all changes in the E2E folder.
> danger: Modify file paths

- CHANGELOG.md
- api/src/authz/intents.ts
- api/src/index.ts
- api/src/service/cache2.ts
- api/src/service/domain/business_event.ts
- api/src/service/domain/organization/user_eventsourcing.ts
- api/src/service/domain/organization/user_permission_grant.spec.ts
- api/src/service/domain/organization/user_permission_grant.ts
- api/src/service/domain/organization/user_permission_granted.ts
- api/src/service/domain/organization/user_permission_revoke.spec.ts
- api/src/service/domain/organization/user_permission_revoke.ts
- api/src/service/domain/organization/user_permission_revoked.ts
- api/src/service/project_permission_revoke.ts
- api/src/service/store.ts
- api/src/service/user_permission_grant.ts
- api/src/service/user_permission_revoke.ts
- api/src/service/user_permissions_list.ts
- api/src/user_permission_grant.ts
- api/src/user_permission_revoke.ts
- api/src/user_permissions_list.ts
The following endpoints have been added:
- user.intent.grantPermission
- user.intent.revokePermission
- user.intent.listPermissions
Unit tests for 'user.intent.grantPermission' and 'user.intent.grantPermission' have been added.
Closes #310
> api: Add user permission endpoints

- dangerfile.js
The check for e2e-tests was done for the "modified" parameter, which is
only true if files are edited, but not if files were added only. The
check was changed to "edited" since this includes both added and
modified files.
> danger: Change check for e2e-test files to edited

- CHANGELOG.md
- api/src/subproject_view_details.ts
- e2e-test/cypress/integration/workflowitem_edit_spec.js
- frontend/src/pages/Common/Identifier.js
- frontend/src/pages/Common/TextInput.js
- frontend/src/pages/Workflows/Workflow.js
- frontend/src/pages/Workflows/WorkflowContainer.js
- frontend/src/pages/Workflows/WorkflowDialogAmount.js
- frontend/src/pages/Workflows/WorkflowItem.js
- frontend/src/pages/Workflows/actions.js
When the subproject details are fetched, the workflow item currency is
now returned as well.
Removed the action 'fetchWorkflowItems' as it is not used.
Closes #281
> api: Send workflow item currency with subproject details

- CHANGELOG.md
- e2e-test/cypress/integration/change_user_password_spec.js
- e2e-test/cypress/integration/groups_spec.js
- e2e-test/cypress/integration/users_spec.js
- e2e-test/cypress/support/commands.js
- frontend/src/pages/Common/AutoComplete.js
- frontend/src/pages/Navbar/SideNav.js
- frontend/src/pages/Navbar/SideNavCard.js
- frontend/src/pages/Users/GroupDialogContent.js
- frontend/src/pages/Users/GroupTable.js
- frontend/src/pages/Users/UserDialogContent.js
- frontend/src/pages/Users/UserManagementContainer.js
- frontend/src/pages/Users/Users.js
- frontend/src/pages/Users/UsersTable.js
- frontend/src/permissions.js
Since every user can now change his/her password, every user should also
be able to see the users table. The check for the permissions global.createUser, global.createGroup and global.listPermissions have been removed.
E2E tests have been added to test this scenario. Additionally, the E2E
tests check for the availability of the buttons to add users and edit
user permissions.
Closes #333 
Create a user with only basic permissions. This user should still see the "Users" menu in the navigation on the left and see the users table.
> ui: Every user can see the user/groups table

- CHANGELOG.md
- doc/wiki/User-Guide/Projects/Project.md
- e2e-test/cypress/integration/currencies_spec.js
- e2e-test/cypress/integration/navigation_spec.js
- e2e-test/cypress/integration/overview_spec.js
- frontend/src/pages/Login/LoginPage.js
- frontend/src/pages/Navbar/LogoutIcon.js
- frontend/src/pages/Navbar/MainNavbarNavigation.js
- frontend/src/pages/Navbar/Navbar.js
- frontend/src/pages/Navbar/NavbarContainer.js
- frontend/src/pages/Navbar/NotificationIcon.js
- frontend/src/pages/Navbar/ProjectSearch.js
- frontend/src/pages/Navbar/RightNavbarNavigation.js
- frontend/src/pages/Navbar/SideNavCard.js
- frontend/src/pages/Navbar/actions.js
- frontend/src/pages/Navbar/reducer.js
- frontend/src/pages/Overview/OverviewContainer.js
- frontend/src/pages/Overview/OverviewTable.js
A new feature is added which lets the user filter the projects in the overview page. 
The button "Quick Search" can be used to toggle the search bar. The term entered in the search bar is used for filtering the projects. When the user navigates to the project details page of a project or clicks on the breadcrumb menu "Main", the search field is cleared and the search bar is no longer displayed.
Closes #347  
Go to the overview page, click the "Quick Search" button and enter a term to filter the projects in the overview page.
> ui: New Search feature

- CHANGELOG.md
- e2e-test/cypress/integration/users_spec.js
- frontend/src/pages/Common/ActionButton.js
- frontend/src/pages/Overview/OverviewTable.js
- frontend/src/pages/SubProjects/SubProjectTable.js
- frontend/src/pages/Users/GroupTable.js
- frontend/src/pages/Users/UsersTable.js
- frontend/src/pages/Workflows/WorkflowItem.js
When the user does not have the permissions to edit the workflow item,
permissions or status, the corresponding action button is not displayed.
Closes #235
> ui: Change display behavior of workflow item buttons

- CHANGELOG.md
- api/src/service/group_query.spec.ts
- api/src/service/group_query.ts
* api: Throw notFoundError if assignee does not exist while assigning a project/subproject/workflowitem
Use postman to try and assign a nonexistent user
Closes #83
> api: Prohibit assign to nonexistent assignee

- CHANGELOG.md
- api/src/service/domain/workflow/project_create.ts
- e2e-test/cypress/integration/change_user_password_spec.js
- e2e-test/cypress/integration/overview_spec.js
- frontend/src/pages/Navbar/Navbar.js
- frontend/src/pages/Navbar/NavbarContainer.js
- frontend/src/pages/Navbar/actions.js
- frontend/src/pages/Navbar/reducer.js
- frontend/src/pages/Overview/OverviewContainer.js
- frontend/src/pages/Overview/OverviewTable.js
- frontend/src/pages/Users/UserManagementContainer.js
- frontend/src/pages/Users/UsersTable.js
* ui: Disable create-project-button  for 'root' user
* ui: Enable edit-user-{user id}-button of all users if 'root' is logged in, thus allow 'root' to change all users passwords
* api: Throw preconditionError if user 'root' tries to create a project
Unit tests for creating projects an editing passwords have been added
Use postman to try and create a project as 'root' user
Closes #366
Closes #379
> Prohibit root from creating projects

- CHANGELOG.md
- e2e-test/cypress/integration/subproject_displayname_spec.js
- frontend/src/helper.js
- frontend/src/languages/english.js
- frontend/src/languages/french.js
- frontend/src/languages/german.js
- frontend/src/languages/portuguese.js
- frontend/src/pages/Common/Budget.js
- frontend/src/pages/Dashboard/DashboardContainer.js
- frontend/src/pages/Notifications/NotificationsSnackbar.js
- frontend/src/pages/Overview/ProjectDialog.js
- frontend/src/pages/SubProjects/ProjectDetails.js
- frontend/src/pages/SubProjects/SubProjectTable.js
- frontend/src/pages/SubProjects/SubprojectDialog.js
- frontend/src/pages/Workflows/SubProjectDetails.js
- frontend/src/pages/Workflows/WorkflowDialog.js
- frontend/src/pages/Workflows/WorkflowDialogAmount.js
* Improve layout of subproject details page by setting each section on
the top to a width of about 32%
* Improve layout of subproject table to include overflow ellipses for
long subproject display names
* Introduce a word wrap for long display names on the project and
subproject details page
* Shorten the project, subproject and workflow item display names for
the snackbar messages
* Add an e2e test which checks that the action buttons are available on
the subproject table even for long display names
* Adapt the projected budget table on project/subproject details page to avoid an
overflow into the next section
* Rename "Workflowitem item details" to "Workflowitem details"
Closes #274 
Closes #233
> ui: Improve subproject details layout and display of display names

- CHANGELOG.md
- api/src/service/domain/workflow/project_permissions_list.spec.ts
- api/src/service/domain/workflow/project_permissions_list.ts
- api/src/service/project_permissions_list.ts
The domain layer of project.intent.listPermissions is missing, so we should add it with the permission check. Currently the endpoint checks the project.viewSummary permission instead of project.intent.listPermissions.
User without project.intent.listPermissions cannot list project permissions
User without project.viewSummary but with project.intent.listPermissions can list project permissions
Closes #393
> api: Create domain layer for project.intent.listPermissions

- CHANGELOG.md
- e2e-test/cypress.json
- e2e-test/cypress/integration/overview_spec.js
- e2e-test/cypress/integration/project_create_spec.js
- e2e-test/cypress/integration/project_edit_spec.js
- e2e-test/cypress/integration/subproject_edit_spec.js
- e2e-test/cypress/integration/workflowitem_edit_spec.js
- e2e-test/cypress/support/commands.js
- frontend/package-lock.json
- frontend/src/pages/Common/ActionButton.js
- frontend/src/pages/Overview/ProjectCard.js
- frontend/src/pages/SubProjects/SubProjectTable.js
It shouldn't be able to view nor click the edit button without update permissions. Currently it is possible to view/click the edit button, but it's not possible to edit on submit.
Closes #395
> UI: Change logic when edit button should be shown

- CHANGELOG.md
- e2e-test/cypress/integration/project_analytics_spec.js
- e2e-test/cypress/integration/subproject_analytics_spec.js
- e2e-test/cypress/support/commands.js
- e2e-test/cypress/support/helper.js
- e2e-test/package-lock.json
- e2e-test/package.json
- frontend/src/languages/english.js
- frontend/src/languages/french.js
- frontend/src/languages/german.js
- frontend/src/languages/portuguese.js
- frontend/src/pages/Analytics/ProjectAnalytics.js
- frontend/src/pages/Analytics/ProjectAnalyticsDialog.js
- frontend/src/pages/Analytics/SubProjectAnalytics.js
- frontend/src/pages/Analytics/SubProjectAnalyticsDialog.js
- frontend/src/pages/Analytics/reducer.js
- frontend/src/pages/SubProjects/ProjectDetails.js
- frontend/src/pages/Workflows/SubProjectDetails.js
- frontend/src/pages/Workflows/WorkflowContainer.js
If a user does not have the permission to see all workflowitems for all subprojects, the project analytics screen displays the message "Insufficient permissions". This is somewhat correct, since in this case the allocated and disbursed amount cannot be calculated. Since there are other values available on the permissions screen it would be a better UI experience if only the values that cannot be calculated are disabled or "redacted".
- If the user has insufficient permission (redaceted workflowitems) only the total budget will be displayed. 
- The feature to convert the budget into the different currencies is also available without these permissions. 
- The insufficient permissions warning is shown below the total budget with an improved style.
> ui: Change analytics access without permissions

- dangerfile.js
- e2e-test/cypress/integration/project_permissions_spec.js
- e2e-test/cypress/integration/subproject_permissions_spec.js
- e2e-test/cypress/integration/workflowitem_permissions_spec.js
- e2e-test/cypress/support/commands.js
- frontend/src/pages/Loading/RefreshIndicator.js
During creation of e2e tests it is common to use the keyword it.only to run one specific test. To avoid that this it.only is not pushed into the repository there should be a warning if the keyword is part of an e2e-test file.
Currently the icons of the e2e-test message in every PR are not suitable.
:warning: e2e tests started
:heavy_check_mark: e2e tests successful
:x: e2e tests failed
:grey_exclamation: e2e tests started
:white_check_mark: e2e tests successful
:x: e2e tests failed
Closes #385 
Closes #383
> Danger: Add check for .only keyword in e2e-tests

- CHANGELOG.md
- e2e-test/cypress/integration/currencies_spec.js
- e2e-test/cypress/integration/language_spec.js
- e2e-test/cypress/support/commands.js
- e2e-test/cypress/support/helper.js
- frontend/src/currency.js
- frontend/src/helper.js
- frontend/src/languages/english.js
- frontend/src/languages/french.js
- frontend/src/languages/german.js
- frontend/src/languages/portuguese.js
- frontend/src/pages/Common/NewDropdown.js
- frontend/src/pages/Login/reducer.js
- frontend/src/reducers.js
Description
Currencies and values should be formatted according to selected language The format includes the position of currency-symbol (before or after value) and the point/comma for thousands/decimal. #135
Furthermore, the set language should be preselected after logging out. #420 
Solution
Added formatting in each language js file:
```
en: 
decimal: ".", thousand: ","
symbol left, value right (eg: € 1,000.00)
de, fr, pt: 
decimal: ",", thousand: "."
symbol right, value left (eg: 1.000,00 €)
```
In action "LOGOUT" the current language is set to the next state
> UI: Currencies and number format depends on language now

- CHANGELOG.md
- e2e-test/cypress/integration/timestamp_spec.js
- frontend/src/helper.js
- frontend/src/pages/Common/HistoryList.js
- frontend/src/pages/Notifications/NotificationListItems.js
New Format according to Issue #426
Old Timestamp depends on current time and is set relative to it (e.g: "a minute ago")
New Timestamp shows absolute values (e.g: "15.01.2020 16:48")
Closes #426
> New Format of timestamp in history and notification

- frontend/src/languages/english.js
Fix a typo in the language selection, where "Georgian" is written as
"Gerogian".
Closes #432
> ui: Fix typo in language selection

- e2e-test/cypress/integration/subproject_search_spec.js
- frontend/src/pages/SubProjects/SubProjectTable.js
The searchbar at subproject-level now remains as displayed.
Closes #474
> Fix subproject searchbar

- .travis.yml
- CHANGELOG.md
- dangerfile.js
- e2e-test/cypress/integration/version_spec.js
- email-notification/package-lock.json
- email-notification/src/db.ts
- excel-export/src/api.ts
- excel-export/src/excel.ts
- frontend/src/pages/Common/Password.js
- frontend/src/pages/Common/Username.js
- frontend/src/pages/Navbar/SideNav.js
- frontend/src/pages/Navbar/reducer.js
In this PR following tasks shall be completed:
- Due to the combination of a log limit of 4MB and a tons of npm audit output the travis audit job would fail. Disabling the npm audit log solves this issue for now.
- Add `workflowitemTypes` and `dueDate` to exported excel sheet #511 
- Add label to password field of user-creation-dialog
- Fix Update statement of email-service. #510 
- Fix display of service versions after location change #512 
- Add danger warning if excel-export project is not adapted after changing a resource (project/subproject/workflowitem) in the api
Last task should prevent a developer to forget adding a new property to the execl-export project.
Closes #510 
Closes #511
Closes #512
> Add missing workflowitem columns to exported excel

- e2e-test/cypress/integration/documents_spec.js
- e2e-test/cypress/integration/global_permissions_spec.js
- e2e-test/cypress/integration/project_close_spec.js
- e2e-test/cypress/integration/subproject_edit_spec.js
- e2e-test/cypress/integration/subproject_permissions_spec.js
- e2e-test/cypress/integration/subproject_search_spec.js
- e2e-test/cypress/integration/workflowitem_create_spec.js
- e2e-test/cypress/integration/workflowitem_edit_spec.js
- e2e-test/cypress/integration/workflowitem_history_spec.js
- e2e-test/cypress/support/commands.js
- frontend/src/pages/Common/Permissions/PermissionSelection.js
- frontend/src/pages/Common/Permissions/PermissionsTable.js
- frontend/src/pages/SubProjects/SubProjectContainer.js
- frontend/src/pages/SubProjects/SubProjectTable.js
- frontend/src/pages/Workflows/WorkflowContainer.js
- frontend/src/pages/Workflows/WorkflowItem.js
**Checklist:**
- Every test shall be independent and can be run by its own (cypress.only())
- If api calls are made in the background cypress has to wait for that route before expecting an element
**Critical test files**:
- `workflowitem_history_spec.js`
- `workflowitem_edit_spec.js`
- `subproject_edit_spec.js`
- Subproject Edit When closing the project, a dialog pops up
- `subproject_permissions_spec.js`
- Subproject Permissions Submitting the permission dialog without any changes doesn't revoke nor grant permissions and close the dialog
- `global_permissions_spec.js`
- `documents.spec`
- Attaching a document to a workflowitem. A document can be validated.
TODO:
Closes #501
> e2e-test: stabilize tests

- api/src/service/domain/workflow/project_history_get.spec.ts
- api/src/service/domain/workflow/project_history_get.ts
- api/src/service/domain/workflow/subproject_history_get.spec.ts
- api/src/service/domain/workflow/subproject_history_get.ts
- api/src/service/domain/workflow/workflowitem_create.ts
- api/src/service/domain/workflow/workflowitem_history_get.spec.ts
- api/src/service/domain/workflow/workflowitem_history_get.ts
For viewing the history, only the intents project.viewHistory, subproject.viewHistory or workflowitem.viewHistory should be used on api level. Currently, to view the history, the api only checks for permissions on workflowitem.view, subproject.viewDetails or project.viewDetails.
To avoid a breaking change the api should allow the request with viewDetails or viewHistory permissions. In Trubudget 2.0.0 this should be changed to only allow the request with viewHistory permission -> #547 
Closes #486
> api: Add check for viewHistory permissions

- blockchain/package-lock.json
- blockchain/package.json
- blockchain/src/index.js
Changed CoreV1Api access (breaking change in k8s client-node module)
Latest version of client-node is not used since it would require too many changes:
- newer node image
- install curl manually in docker file
- check root cause of warnings similar to https://github.com/nodejs/node/issues/32987
> Update kubernetes client-node module

- api/package.json
- doc/tutorials/contribute/Contributor-Guide.md
Changes to the contribution guide were needed for successful launch in DEV mode.Necessity of changes was confirmed by new contributors also working on macs.
Although typescript is listed in dependencies, I had an older version of TS compiler installed globally and in PATH, which resulted in incorrect transpiling of source to JS, namely optional chaining wasn't recognized by node 14 (which it should?), so I added a memo.
Issue #589
> Contributor guide update

- CHANGELOG.md
- README.md
- doc/tutorials/working-with-the-api/working-with-the-api.md
- e2e-test/cypress/integration/workflowitem_edit_spec.js
- frontend/src/pages/Confirmation/ConfirmationContainer.js
- frontend/src/pages/Confirmation/ConfirmationDialog.js
- frontend/src/pages/Confirmation/reducer.js
- frontend/src/sagas.js
If a user has permission to close a workflowitem BUT no permission to list permissions of the workflowitem (workflowitem.intent.listPermissions), the confirmation dialog throws an error. The reason is that the confirmation dialog fetches permission of workflowitem by default, which is not necessary for the closing a   workflowitem. This also applies to project, subproject
Closes #562 
Closes #544
> Fix falsy permission fetching in Confirmation Dialog

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- api/.eslintrc.yaml
Closes #592 
Added recommended extension to workspace configuration for vscode.
`.vscode` was included in gitgnore
Restart of vscode might be needed after pulling the changes.
> added recommendation for extensions in workspace

- .vscode/launch.json
- api/src/service/user_authenticate.ts
- provisioning/package.json
Closes #561 
There was an unhandled exception in `getOrganizationAddressItem` in `api/src/organization/organization.ts` - multichain is `undefined`;
Perhaps it would be good to handle it in upper function call, `authenticateRoot` could check if it's not passing `undefined` arguments to  functions it calls. 
To replicate the bug, one way is to temporarily replace  in `api/src/index.ts`
`  const db = Multichain.init(rpcSettings);`   with   `const db = {};` and launch provisioning.
Provisioning exited fast, so it was not possible to attach a debugger. Added a launch configuration for debugging the service.
> unhandled error in request handler

- e2e-test/cypress/support/commands.js
This PR fixes the timeout issue in the backup_spec e2e-test, by increasing the timeout from the default 30 seconds to 60 seconds. Sometimes the request might take more than 30 seconds to finish, which is why the test failed.
Closes #630
> e2e-test: Add timeout to the createBackup request

- e2e-test/cypress/integration/subproject_close_spec.js
- e2e-test/cypress/integration/workflowitem_close_spec.js
* E2E tests for closing subproject were added 
* E2E tests for closing a project and workflow item already there
Closes #623
> E2E tests for item closing

- CHANGELOG.md
- frontend/src/pages/Workflows/WorkflowBatchEditContainer.js
- frontend/src/pages/Workflows/WorkflowEditDrawer.js
Added groups to batch permission assignment. One or more groups could be set for multiple workflowitems.
Closes #612
> ui: added groups to batch permission assignment

- frontend/src/pages/Workflows/WorkflowBatchEditContainer.js
- frontend/src/pages/Workflows/WorkflowEditDrawer.js
- [c] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/master/CONTRIBUTING.md).
Fixing bug in already closed tasks #612 
Selecting correct groups from state.
Closes #680
> ui:fixing incorrect state for groups

- frontend/src/pages/Confirmation/validation.js
The Joi Validation of dueDate on frontend/client side is set to string(empty Value `""`) instead of date (empty Value `null`).
This PR solves the currently failing e2e-tests.
The validation additionally allows empty base64 values for documents
> ui: Fix joi validation of dueDate

- api/.eslintrc.yaml
- api/src/workflowitem_download_document.ts
new Buffer() expression was deprecated and replaced with Buffer.from() 
I updated the code and manually tested to verify the functionality is the same. 
To test, dowload a document attached to workflowitem.
Closes #681
> api: Fix deprecated buffer and remov rule override

- .vscode/launch.json
- docker-compose/development/docker-compose.yml
- excel-export/package.json
* Fixed Excel Export service: Set correct host name
* Excel Export's sources are hot reloaded
* Added VS Code run debug configuration for Excel Export
* Added VS Code launch Chrome configuration for debugging frontend in Docker container
Closes #667
> Debugging code in Docker container

- CHANGELOG.md
- e2e-test/cypress/integration/project_assignee_spec.js
- e2e-test/cypress/integration/workflowitem_types_spec.js
- frontend/src/pages/Common/OverflowTooltip.js
- frontend/src/pages/Common/Permissions/PermissionSelection.js
- frontend/src/pages/Common/SingleSelection.js
- frontend/src/pages/Workflows/WorkflowEditDrawer.js
The assignee selection in workflowitem batch editing is too wide.
Closes #678
> ui: fix width of dropdown in workflowitem-batch edit

- e2e-test/cypress/integration/excel_export_spec.js
- frontend/src/api.js
**Summary**
* Helper functions for returning URL for Excel Export service and E-mail Service dynamically
* Where: frontend service
**Issue**
* Closes #450
**Test Plan**
* Development mode: 
* Replace `docker-compose/development/docker-compose.yml` with `docker-compose.yml` from test-yaml.zip
* Run Docker Compose for Dev (`sh scripts/development/start-dev.sh`)
* Production mode: 
* Replace `docker-compose/local/master-node.yml` with `master-node.yml` from test-yaml.zip
* Run Docker Compose for Local Master (`sh scripts/local/start-and-provision-master-node.sh`)
* In both modes:
* Check status for both services (hamburger icon -> wrench icon)
* Export projects list to Excel Sheet with left sidebar button Export
* Add/edit email address (hamburger icon -> gear icon)
**Attachments**
* …
> ui: Remove hardcoded paths

- api/.eslintrc.yaml
- api/src/notification_list.ts
- api/src/service/domain/workflow/workflowitem_ordering.spec.ts
- api/src/service/domain/workflow/workflowitem_update.spec.ts
This PR removes @typescript-eslint/prefer-as-const: 0 from global eslint overrides in api, in favor of local overrides.
Rule has been deleted from eslintrc file, because it is 2 by default in our current configuration. No need to explicitly set rule level to 2.
Closes #729
> api: Add overrides for default prefer-as-const rul

- frontend/.eslintrc
- frontend/src/pages/Common/DatePicker.js
- frontend/src/pages/Confirmation/validation.js
- frontend/src/pages/Login/PrivateRoute.js
- frontend/src/pages/Main/Footer.js
- frontend/src/pages/Main/Placeholder.js
This PR adds eslint rules for semicolons and spaces before function params. 
Rules are set up in a way to conform to existing style, and enforce it where it doesn't.
Contains also fixes of those few files.
Closes #740
> frontend: Set eslint semi rules and paren space

- CHANGELOG.md
- e2e-test/cypress/integration/subproject_permissions_spec.js
- e2e-test/cypress/integration/workflowitem_permissions_spec.js
- frontend/src/pages/Confirmation/createAdditionalActions.js
In the confirmation dialog, the listpermission which may be required for other intents were not set correctly.
Following intents are affected for listPermissions:
```
subproject.createWorkflowitem 
subproject.assign 
subproject.intent.grantPermission
subproject.intent.revokePermission
project.createSubproject
project.assign
project.intent.grantPermission
project.intent.revokePermission
workflowitem.assign
workflowitem.intent.grantPermission
workflowitem.intent.revokePermission
```
Closes #738
> ui: fix additional listPermission requirements

- CHANGELOG.md
- e2e-test/cypress/integration/suproject_view_details_spec.js
- frontend/src/pages/Workflows/WorkflowItem.js
> ui: add attachment file icon in workflow

- CHANGELOG.md
- api/src/httpd/schema.ts
- api/src/network/controller/list.ts
- api/src/network/model/Nodes.ts
- api/src/service/Client.h.ts
- api/src/service/Client.ts
- e2e-test/cypress/integration/nodes_spec.js
- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Common/CreationDialogStepper.js
- frontend/src/pages/Common/History/eventTypes.js
- frontend/src/pages/Common/images.js
- frontend/src/pages/Login/PrivateRoute.js
- frontend/src/pages/Nodes/NodeVoting.js
- frontend/src/pages/Nodes/NodesTable.js
- frontend/src/pages/Workflows/WorkflowItem.js
- frontend/src/pages/Workflows/compareWorkflowItems.js
* Display connection status of each node in the network list (/nodes page)
* Used `getpeerinfo` to retrieve all connected peers, compare with node list to determine status
1. in scripts/development/docker-compose.yml add following service right after *master-node*:
```
slave-node:
build:
context: ../../blockchain
environment:
ORGANIZATION: ${ORGANIZATION}
RPC_PORT: ${RPC_PORT}
RPC_PASSWORD: ${RPC_PASSWORD}
P2P_HOST: master-node
P2P_PORT: ${P2P_PORT}
API_PROTO: http
API_HOST: master-api
API_PORT: ${API_PORT}
EXTERNAL_IP: master-node
volumes:
- /tmp/bcSlaveVolume:/root/.multichain
ports:
- "7448:7447"
```
2. Run app as normal, approve new node and check that Network table on /nodes page **displays** two nodes with **Connection** status 
3. In new terminal window run `docker exec -it …
> Node Connection Status

- api/package.json
- blockchain/package-lock.json
- blockchain/package.json
- blockchain/src/index.js
- docker-compose/multi/multi-nodes.yml
- provisioning/package.json
- scripts/multi/start-multi.sh
No CHANGELOG added, because end user is not afected.
Since separate frontends for master and slave nodes are required, that means separate api services are needed. 
Slave node needs to communicate with both master and and its own api. That required a change in blockchain and setting up appropriate envirornment variables.  If new environment variables are not set, application reverts to the original variables, and behaves the same as before. This ensures backwards compatibility. 
Slave node requests permissions to conenct to chain via master api, which is possible to grant in frontend. Previously, if a slave node used its own api, and without new configuration, it could be done only through multichain cli, and end users didn't notice request to join. Logical, since a new node might be …
> Create docker-compose for multiple nodes #748

- CHANGELOG.md
- api/src/index.ts
- api/src/service/RpcClient.ts
- api/src/service/domain/document/document.ts
Files over 10mb could not be uploaded. By default, axios sets its maxBodyLength at 10mb, so this had to be increased. But since the files are sent to the api as base64, and multichain only accepts files up to 50mb, the limit had to be the equivalent of 50mb base64.
TODOs:
Closes #843
> Fix file size limit - 50mb

- api/src/service/RpcClient.ts
- api/src/service/cache2.ts
- api/src/service/liststreamitems.ts
This PR is fixing a bug where the cache of Trubudget's api cannot handle corrupt blockchain events. Instead of throwing an UNHANDLED PROMISE REJECTION the api should ignore corrupt events and print out a warning that the event cannot be read.
> api: Refactor retrieve items of rpcClient

- api/src/service/domain/workflow/workflowitem_permission_grant.ts
When granting a permission on a workflowitem with attached document to a group. An Error will be thrown.
1) Start Trubudget With Document Storage Service Feature
2) Login as Admin
3) Create a Group and add 1 Test User
4) Create a Project & Sub-Project
5) Create a Workflow-Item and attach a document in the creation process
6) Try to give the created group any permission (for example view permission) on that workflow-item
Exception will Occur
Closes #938"
> Bugfix: Exception when granting workflowitem permission on group

- CHANGELOG.md
- api/src/index.ts
- api/src/service/domain/document/document.ts
- api/src/service/domain/workflow/workflowitem_get_details.spec.ts
- api/src/service/domain/workflow/workflowitem_get_details.ts
- api/src/service/workflowitem_get_details.ts
- api/src/workflowitem_list.ts
- api/src/workflowitem_view_details.ts
- frontend/src/api.js
- frontend/src/languages/english.js
- frontend/src/languages/french.js
- frontend/src/languages/georgian.js
- frontend/src/languages/german.js
- frontend/src/languages/portuguese.js
- frontend/src/pages/Documents/DocumentOverview.js
- frontend/src/pages/Workflows/WorkflowContainer.js
- frontend/src/pages/Workflows/WorkflowDetails.js
- frontend/src/pages/Workflows/WorkflowItem.js
- frontend/src/pages/Workflows/WorkflowTable.js
- frontend/src/pages/Workflows/actions.js
- frontend/src/pages/Workflows/reducer.js
- frontend/src/sagas.js
In order to check whether documents in a workflowitem are available or not, the api must first try to download the document to mark it as available or not. This will be done in a new endpoint `workflowitem.viewDetails`, that is triggered when a workflowitem is clicked. 
Closes #944
> Add workflowitem.viewDetails endpoint

- scripts/development/docker-compose.yml
- storage-service/src/minio.ts
When restarting minio without persisted data, the storage-service does not re-create the bucket (its like a database-name) on minio, which leads to an error. 
Storage-service should always check if the bucket exists on minio. If it does not exist, re-create it.
To reproduce the problem (for testing), see #946
Closes #946
> Fix minio and storage-service synchronization

- api/src/service/domain/workflow/project_permission_revoke.ts
- api/src/service/domain/workflow/subproject_permission_revoke.ts
- api/src/service/domain/workflow/workflowitem_permission_revoke.ts
- storage-service/src/index.ts
- storage-service/src/minio.ts
Follow up of https://github.com/openkfw/TruBudget/issues/946
Instead of verifying that a valid minio bucket exists, the storage-service will throw an error with an explicit message to restart storage-service to initialize the minio container correctly (hence, a minio bucket will be created).
To reproduce a setup with storage-service and minio, but without a minio bucket, see #946
Closes #972
Reverts commits from #953
> Fix simultaneous document upload

- README.md
Fixed some issues with the root README.md
- The root readme had a link to the TruBudget Wiki, which is not in use. Replaced with link to the documentation on the Trubudget Website.
- Some paragraphs were missing a subtitle and a link to the specific file
Closes #980
> Fix root README.md

- CHANGELOG.md
- api/src/service/domain/organization/group_create.spec.ts
- api/src/service/domain/organization/group_create.ts
- api/src/service/domain/organization/user_create.spec.ts
- api/src/service/domain/organization/user_create.ts
- api/src/service/group_create.ts
- api/src/service/user_create.ts
It should not be possible to create a group or a user with an id that is already taken (by a user or a group). So far the check was only done for users on user creation and for groups on group creation. Now both are checked in either case
Closes #943
> Add check for user and group name

- frontend/nginx.conf
The swagger documentation doesn't work in deployment besides from localhost.
This PR adds a few csp header entries to the nginx of Trubudget's frontend
> ui: Adapt CSP header in nginx config 

- .github/workflows/audit/action.yml
- api/package-lock.json
- api/package.json
- api/src/service/RpcClient.ts
- api/src/service/cache2.ts
- api/src/service/domain/workflow/workflowitem_eventsourcing.ts
- blockchain/.nsprc
- blockchain/package-lock.json
- blockchain/package.json
- bump-tag-versions.sh
- e2e-test/package-lock.json
- e2e-test/package.json
- email-notification-service/package-lock.json
- email-notification-service/package.json
- excel-export-service/package-lock.json
- excel-export-service/package.json
- frontend/package-lock.json
- frontend/package.json
- logging-service/package-lock.json
- logging-service/package.json
- provisioning/package-lock.json
- provisioning/package.json
- storage-service/package-lock.json
- storage-service/package.json
This PR is only a workarround. The main issue is that documents stored via mutlichains offchain mechanic are stored in trubudget's cache. In a future fix these documents should not be part of the cache anymore.
Tasks done in this PR:
- Skip and log errors happening while converting to readable items
- Adapt error messages including all necessary information
- Eventsourcing of workflowitems skip the workflowitem_document_uploaded event since document uploads are handled via workflowitem_update event
It was not possible to exclude certain vulnerabilities to pass the audit checks if there is no fix for the vulnerability yet.
With the new package better-npm-audit you can exclude vulnerabilities with a command argument or with a file called `.nsprc`.
Closes #1017
> api is not exiting on unknown Event type

- .github/workflows/github-ci.yml
- api/src/lib/joiValidation.spec.ts
- api/src/lib/joiValidation.ts
The api's validation on normal fields are to restrictive. In some languages apostrophes are used quite often so they should be allowed in e.g. description fields. In Id or passwords fields they are still not allowed.
> Add all apostrophe types to api string validation

- .github/workflows/github-ci.yml
- api/src/service/cache2.ts
The fix in #1024 was not sufficient. The documents were still uploaded to the cache because of a bug in how the  filter in the document caching was applied
Closes #1022
> Fix filter in document caching

- api/src/service/workflowitem_document_download.ts
Add a fix to a bug in #1024 where all events from the `offchain_documents` stream were loaded as offchain docs, instead of just events with type `workflowitem_document_uploaded`. This caused errors when getting docs stored in the external storage service.
> Fix bug in getting offchain docs

- blockchain/src/connectToChain.js
Fix log output on multichain error
In this PR 
- multichain logs are changed to debug level instead of info since it's not very readable on log_level info
- a log output is fixed where only a buffer was shown instead of the actual readable error message
> Change multichain logs to debug level

- provisioning/README.md
The provisioning data is now described in the README.md.
> Describe Provisioning data in README.md

- api/package-lock.json
- api/package.json
- api/src/service/Client.ts
- api/src/service/RpcClient.ts
- api/src/service/cache2.ts
- api/src/service/document_get.ts
- api/src/service/global_permission_grant.ts
- api/src/service/global_permission_revoke.ts
- api/src/service/global_permissions_get.ts
- api/src/service/notification_list.ts
- api/src/service/public_key_get.ts
- api/src/service/subproject_list.ts
- api/src/service/user_assignments_get.ts
- api/src/service/workflowitem_permission_grant.ts
- api/src/service/workflowitem_permission_revoke.ts
- api/src/service/workflowitem_permissions_list.ts
- api/src/system/getVersion.ts
- e2e-test/cypress/integration/documents_spec.js
- frontend/Dockerfile.dev
- frontend/hotReloadSetup.js
- frontend/package.json
Hot reloading is broken in react-scripts, more information: https://github.com/facebook/create-react-app/issues/11879
This PR fixes the hot reloading with an additional script.
> ui: fix hot reloading for docker and bare metal

- CHANGELOG.md
- api/package-lock.json
- api/package.json
- api/src/service/Client_storage_service.ts
- api/src/workflowitem_download_document.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/api.js
Upload of documents failed if file name contained special characters. MinIO does not support special characters in the metadata field (where the file name was saved).
Closes #1054
> Special chars in fileName fix

- api/src/service/Client_storage_service.ts
- provisioning/src/lib.js
> api: Fix storage service readiness call

- storage-service/src/index.ts
- storage-service/src/minio.ts
> storage-service: Check minio status on readiness

- blockchain/package-lock.json
- docker-compose/README.md
- docker-compose/blockchain/docker-compose.alphanode.yml
- docker-compose/blockchain/persistence.docker-compose.yml
This PR changes the bind-mount persistence of blockchain's docker-compose file to volume since it's not possible to mount a folder with bind-mount with the latest blockchain image. 
The latest image is using a non-root user. Using volumes there is no issue, but using bind-mount the folder on the host system has to have permissions set to the non-root user in the container which could be a user not existing on the host.
There is also a doc section added.
> Change blockchain persistence to volumes

- CHANGELOG.md
- api/src/service/domain/workflow/workflowitem_create.spec.ts
- api/src/service/domain/workflow/workflowitem_create.ts
- api/src/service/workflowitem_create.ts
2 validations on API Level are added:
1- Disabled users are not allowed to be assigned to workflow items.
2- Users that do not exist are not allowed to be assigned to workflow items.
Closes #1327
> Validate assignee when creating workflow item

- api/src/httpd/router.ts
- storage-service/package-lock.json
Closes #1367 
Added additional check for the token inside error. If it is undefined, userId is not printed in the log.
> api:additional check for token inside error

- frontend/configureServer.sh
- frontend/nginx.conf
Url for exchange rate API changed. For production build, nginx configuration needs to be updated. We also want to make it configurable with with environment variables.
When REACT_APP_EXCHANGE_RATE_URL is set, nginx is automatically updated with this value during build time.
Closes #1405
> ui: update nginx to allow new exchange rate url

- e2e-test/cypress/integration/users_spec.js
- frontend/src/pages/Users/Dialog.js
- frontend/src/pages/Users/UserDialogContent.js
Password validation in backend is turned on only if `NODE_ENV == production`. For testing purposes, either set the environment variable to production, or enforce strict `safePasswordSchema` in `api/src/lib/joiValidation.ts`.
Provisioning users, however, fails under these conditions, because their passwords do not meet the conditions.
Requirements are at least 8 characters, at least 1 number, at least one letter. 
Closes #1421
> fe: add fe password validation when creating user

- frontend/src/pages/Overview/TableView.js
> ui: fix inifinite render

- .github/workflows/github-ci.yml
- scripts/pipeline/publish-docker-images.sh
extend github actions to also push images to [quay.io/trubudget](https://quay.io/organization/trubudget)
- added robot to action secrets
- updated github build action
> add push to quay.io

- frontend/src/pages/Navbar/SideNavCard.js
- frontend/src/pages/Overview/reducer.js
`<ListItem button` had been deprecated.
Due to failing tests, project updates had to be paused when editing additional data, otherwise re-render discarded any changes. IDK how were the tests passing until now.
Closes #1444
> ui: replace deprecated ListItem button in side nav

- blockchain/package-lock.json
Bump get-func-name from 2.0.0 to 2.0.2 to address a new security vulnerability.
> bc:bumped get-func-name to 2.0.2 to fix a security vulnerability

- api/src/httpd/server.ts
- api/src/user_authenticate.ts
- e2e-test/cypress/integration/excel_export_spec.js
- e2e-test/cypress/integration/subproject_permissions_spec.js
- e2e-test/cypress/integration/users_spec.js
- e2e-test/cypress/integration/workflowitem_permissions_spec.js
- e2e-test/cypress/plugins/index.js
- e2e-test/cypress/support/commands.js
- excel-export-service/src/index.ts
- frontend/src/api.js
- frontend/src/localStorage.js
- frontend/src/pages/Login/LoginPageContainer.js
- frontend/src/pages/Login/reducer.js
- frontend/src/pages/Notifications/NotificationPageContainer.js
- frontend/src/sagas.js
- provisioning/src/api.js
The PR [improvement of cookie management](https://github.com/openkfw/TruBudget/pull/1287/files#diff-02a570b6695e4fbb6f3525f5e5e534125d1a2d4cd05600d88c5cd47db6bbe6b3) adds a cookie based authentication, but there are still unused remains of jwt token logic being stored in Redux and browser's local storage. This PR removes the unused jwt token references from the ui and e2e-tests.
Closes #1453
> 1453 remove jwt from storage

- frontend/src/pages/Analytics/ProjectAnalyticsDialog.js
- frontend/src/pages/Analytics/SubProjectAnalytics.js
- frontend/src/pages/Analytics/SubProjectAnalyticsDialog.js
> ui: set default analytics currency

- CHANGELOG.md
- api/src/index.ts
- api/src/user_logout.ts
- frontend/src/api.js
- frontend/src/sagas.js
> api: implement secure logout

- frontend/src/pages/Overview/OverviewContainer.js
- frontend/src/pages/Overview/TableView.js
- frontend/src/pages/Overview/actions.js
- frontend/src/pages/Overview/reducer.js
When user switches to a table view on projects page, and filters projects using a search bar, the projects are correctly filtered. However, these search results are reset in t < 5s. This is due to live update triggering re-render in table view (but not in card view).
Solution is to pause live updates of projects while user is using the search functionality. - Notifications are not affected.
Closes #1536
> frontend: disable live updates when searching

- api/src/service/domain/workflow/workflowitem_eventsourcing.ts
- api/src/service/domain/workflow/workflowitem_ordering.ts
> api: source with log

- frontend/src/pages/Common/Permissions/PermissionSelection.js
- frontend/src/pages/Common/SingleSelection.js
- frontend/src/pages/Confirmation/ActionsTable.js
> frontend: accomodate SingleSelection to content

- email-notification-service/package-lock.json
- email-notification-service/package.json
- email-notification-service/src/index.ts
- excel-export-service/package-lock.json
- excel-export-service/package.json
- excel-export-service/src/index.ts
- storage-service/package-lock.json
- storage-service/package.json
- storage-service/src/index.ts
Removing/changing security headers using helmet default recommended settings.
[Content-Security-Policy](https://www.npmjs.com/package/helmet#content-security-policy): A powerful allow-list of what can happen on your page which mitigates many attacks
[Cross-Origin-Opener-Policy](https://www.npmjs.com/package/helmet#cross-origin-opener-policy): Helps process-isolate your page
[Cross-Origin-Resource-Policy](https://www.npmjs.com/package/helmet#cross-origin-resource-policy): Blocks others from loading your resources cross-origin
[Origin-Agent-Cluster](https://www.npmjs.com/package/helmet#origin-agent-cluster): Changes process isolation to be origin-based
[Referrer-Policy](https://www.npmjs.com/package/helmet#referrer-policy): Controls the …
> 1655 remove header

- frontend/src/languages/english.js
- frontend/src/languages/french.js
- frontend/src/languages/georgian.js
- frontend/src/languages/german.js
- frontend/src/languages/portuguese.js
- frontend/src/pages/SubProjects/SubprojectDialogContent.js
- Add warning message into Subproject form in regards to improving UX flow, so that user can see important info that once he assign Default assignee, he cannot be changed
- accurate translations will be added later
Closes #1720 
> Frontend: modify subproject form flow for default aassignee

- docs/developer/developer-setup.md
I was looking at the documentation in order to set up a local TruBudget environment and I noticed that the url for the `ssh` section was actually the `https` one, thought it would be good to change it
> doc: add proper link for ssh cloning

- frontend/src/pages/Nodes/ApprovedNodesTableEntry.js
- frontend/src/pages/Nodes/ApprovedNodesTableEntry.scss
- fixes approved nodes table cells overflow
- responsive resizing of cells optimised to screen size of 768px
2. go to Nodes tab and scroll to Approved Nodes table
3. unwrap specific node and open developer tools
4. keep resizing browser window from 768px up
5. overflow of items in nodes table should not be present
Closes #1788
> 1788 Fix overflow of nodes table cells

- frontend/src/pages/Common/Budget.js
- frontend/src/pages/Common/Budget.scss
- frontend/src/pages/Common/NewDropdown.js
- optimise styles of budget row in Project and Sub project dialogs
- this is to prevent horizontal scroll bars appearing, hiding fields and buttons and forcing user to scroll add budget
2. open Create/Edit project dialog
3. resize browser window and see that in smaller size the budget row in dialog changes
4. try the same in Sub project dialog
Closes #1790
> 1790 Optimise project and subproject dialog styles

- frontend/src/pages/Overview/ProjectCard.scss
- frontend/src/pages/SubProjects/ProjectDetails.scss
- frontend/src/pages/Workflows/SubProjectDetails.scss
- removed overflowing of project, sub project assignee on desktop and tablet resolution in project/sub project details
- removed resizing of project cards and therefore prevent cards to be one bigger than the other in specific resolutions
2. resize the browser window
3. project card is no longer changing its size
4. project and sub project details overflowing is not present on desktop neither tablet resolution
Closes #1798
> 1798 Optimisation of width in project and sub project

- e2e-test/cypress/integration/project_budget_spec.js
- frontend/src/pages/Overview/CardView.js
- provisioning/src/data/test/amazon_fund.json
- provisioning/src/data/test/biodiversity.json
- provisioning/src/data/test/close_test.json
- provisioning/src/data/test/multiple_donors_1.json
- provisioning/src/data/test/multiple_donors_2.json
- provisioning/src/data/test/school.json
- scripts/operation/docker-compose.yml
Amazonas is provisioned with jpg image as background, but ui shows the new webp image instead.
4. ...
Closes #1814
> ui: webp backward compatibility

- scripts/development/start-dev.sh
1. Start --full environment
2. Test sopping/restarting/rebuilding of selected service e.g. run in secont terminal `bash scripts/development/start-dev.sh --restart-only storage-service`
3. Test is service is rebuilded and rest of the environment is intact
4. ...
Closes #1839
> 1839 Add option to rebuild+restart only one/selected service(s).

- frontend/src/pages/Workflows/WorkflowItem.js
- frontend/src/pages/Workflows/WorkflowItem.scss
- removed problem where long workflow item title breaks the UI layout
- now it can only grow to 2 lines of text
- there is tooltip present so that user can view the whole title if he wants
1. login
2. go to project-> subproject -> create workflow item
3. give workflow item unusual long title and click submit
4. see that title is not breaking UI layout and on hover you can see the tooltip with the whole title
Closes #1850
> 1850 Long worfklow item title breaks layout

- e2e-test/cypress/integration/subproject_create_spec.js
- frontend/src/languages/english.js
- frontend/src/languages/french.js
- frontend/src/languages/georgian.js
- frontend/src/languages/german.js
- frontend/src/languages/portuguese.js
1. Validate translations
4. ...
Closes #1865
> 1865 Change default to fixed assignee

- helm/api/templates/deployment.yaml
- helm/api/values.yaml
- [X ] I fixed all necessary PR warnings
- [ X] The commit history is clean
- [ X] If possible, the issue has been divided into more subtasks
- [X ] I did a self review before requesting a review from another team member
Creating sandboxes fails because the api pod is killed before it reaches liveness. Setting a very high value for initialDelaySeconds prevents being killed in this phase. The initial phase takes very long because filling the database with sample data takes quite a time.
Timeouts are environment specific. A final test can only be done on the final (prod) systems.
> set high default api initialDelaySeconds

- api/src/httpd/router.ts
- api/src/lib/readiness.ts
- provisioning/src/api.js
- provisioning/src/users_and_groups.js
> provisioning: improvement

- api/src/authenticationUtils.ts
- api/src/index.ts
- api/src/user_authenticate.ts
- api/src/user_authenticateAd.ts
- api/src/user_refreshToken.ts
1. Start auth proxy
2. Login with auth proxy
3. Refresh token should work
Closes #2000
> api: Refresh token in authenticateAd route

- frontend/src/pages/Overview/ProjectDialog.js
When editing a project and only deleting tags, submit button is disabled.
1. edit a project that has one or more tags
2. delete a tag
3. submit button should be enabled
4. ...
Closes #2026
> ui: fixed deleting tags

- .github/workflows/update-documentation.yml
- build-docs.sh
- package.json
> 1943 docs fix

- api/src/envVarsSchema.ts
- scripts/development/.env.example
- scripts/development/docker-compose.yml
1. Start app with empty "SILENCE_LOGGING_ON_FREQUENT_ROUTES" variable
2.
> api:Update validation of env vars
